#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -euf -o pipefail
IFS=$'\n\t'

export FROM_POST_MERGE=1
echo "[HOOK] post-merge"

#
# UPDATE CFG
#
# readarray -t LIST_MERGED_FILES < <(git diff --name-only HEAD~1)
# UPDATE_CFG=0
# for MERGED_FILE in "${LIST_MERGED_FILES[@]}"; do
#   if [[ $MERGED_FILE =~ ^TEST\/ ]]; then
#
#     UPDATE_CFG=1
#   fi
# done
#
# if [[ $UPDATE_CFG -eq 1 ]]; then
#   pushd . &>/dev/null
#   cd TEST
#   echo "Updating home-settings dotfiles..."
#   ./install.sh >/dev/null || echo "Error."
#   popd &>/dev/null
# fi
