;;; Directory Local Variables         -*- no-byte-compile: t; -*-

((nil . (;; pre-commit-elisp .dir-locals.el - https://github.com/jamescherti/pre-commit-elisp
         (pre-commit-elisp-load-path . ("home/.emacs-use-package.d/lisp/local/"
                                        "../../emacs/lightemacs/"))
         (pre-commit-elisp-error-on-compile-warning . t)
         ;; Other
         (indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 80)
         (sentence-end-double-space . nil)
         ;; (whitespace-style face tabs trailing lines-tail)
         ;; (whitespace-line-column . 80)
         (require-final-newline . t)))
 ;; (html-mode . ((tab-width . 2)
 ;;               (css-indent-offset . 2)
 ;;               (js-indent-level . 2)))
 ;; (js2-mode . ((tab-width . 2)
 ;;              (css-indent-offset . 2)
 ;;              (js-indent-level . 2)
 ;;              (js2-strict-missing-semi-warning . nil)))
 ;; (js-mode . ((js-indent-level . 2)
 ;;             (css-indent-offset . 2)))
 (emacs-lisp-mode . ((tab-width . 2)
                     ;; (flycheck-disabled-checkers . (emacs-lisp-checkdoc))
                     ;; (compile-command . "make install")
                     (emacs-lisp-docstring-fill-column . 72)
                     (electric-quote-comment . nil)
                     (electric-quote-string . nil)))
 ;; LUA
 (lua-mode . (lua-indent-level . 2))
 (lua-ts-mode . (lua-ts-indent-offset . 2))
 ;; Python
 ;; (python-ts-mode . ((python-indent-offset . 4)
 ;;                    (python-indent-guess-indent-offset-verbose . nil)))
 ;; (python-mode . ((python-indent-offset . 4)
 ;;                 (python-indent-guess-indent-offset-verbose . nil)))
 (python-base-mode . ((python-indent-offset . 4)
                       (python-indent-guess-indent-offset-verbose . nil)))
 ;; Sh or Bash
 (bash-ts-mode . ((tab-width . 2)
                  (sh-basic-offset . 2)
                  (sh-indent-after-continuation . 'always)))
 (sh-mode . ((tab-width . 2)
             (sh-basic-offset . 2)
             (sh-indent-after-continuation . 'always)))
 ;; YAML
 (ansible-mode . ((tab-width . 2)
                  (yaml-indent-offset . 2)))
 (yaml-ts-mode . ((tab-width . 2)))
 (yaml-mode . ((tab-width . 2)
               (yaml-indent-offset . 2)))
 ;; PHP
 (php-ts-mode . ((php-ts-indent-offset . 4)))
 (php-mode . ((c-basic-offset . 4))))
