;;; config.el --- config -*- no-byte-compile: t; lexical-binding: t -*-

;; Author: James Cherti
;; URL: https://github.com/jamescherti/jc-dev
;;
;; Distributed under terms of the MIT license.
;;
;; Copyright (C) 2004-2026 James Cherti
;;
;; Permission is hereby granted, free of charge, to any person obtaining a copy
;; of this software and associated documentation files (the “Software”), to deal
;; in the Software without restriction, including without limitation the rights
;; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
;; copies of the Software, and to permit persons to whom the Software is
;; furnished to do so, subject to the following conditions:
;;
;; The above copyright notice and this permission notice shall be included in all
;; copies or substantial portions of the Software.
;;
;; THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
;; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;; SOFTWARE.

;;; Commentary:

;;; Code:

;;; External config

(load (expand-file-name "~/.config.el") :no-error :no-message :nosuffix)

;;; Optimization

(setq minimal-emacs-inhibit-message-during-startup t)
(setq minimal-emacs-inhibit-redisplay-during-startup t)

(setq site-run-file nil)
(setq inhibit-default-init t)

;; TODO remove from devemacs and my emacs and add this to lightemacs
(with-eval-after-load 'cus-edit
  ;; Prevent Emacs from writing custom settings to any file
  (advice-add 'custom-save-all :override #'ignore))

;;; Native-compilation

(setq enable-dir-local-variables t)
(setq enable-local-variables :safe)

(setq native-comp-jit-compilation t)
(setq native-comp-deferred-compilation t)
(setq package-native-compile t)

;;; Config

;; (setq lightemacs-theme-default-font "Iosevka Medium")
;; (setq lightemacs-theme-default-font "Iosevka SemiBold")
(setq lightemacs-theme-default-font "Iosevka Term SemiBold")

(setq lightemacs-load-compiled-init-files t)
(setq lightemacs-saveplace-recenter-after-find-file t)

(setq minimal-emacs-frame-title-format "Devemacs")

(setq lightemacs-dired-omit-parent-directory t)
(setq lightemacs-cycle nil)
(setq lightemacs-theme-name 'tomorrow-night-deepblue)
(setq lightemacs-theme-package 'tomorrow-night-deepblue-theme)

(setq lightemacs-modules '(le-flavor-micro
                           le-pathaction
                           le-maybe-markdown-ts
                           le-group-evil
                           le-persist-text-scale
                           le-xclip

                           le-compile-angel

                           ;; le-org
                           ;; le-consult
                           ;; le-vertico
                           ;; le-autorevert
                           ;; le-undo-fu
                           ;; le-undo-fu-session

                           ;; le-consult-dir
                           ;; le-embark-consult
                           ;; le-embark
                           ;; le-wgrep
                           ;; le-orderless

                           ;; le-evil-visualstar
                           ;; le-git-modes
                           ))

;;; Ido

(setq ido-everywhere t
      ido-enable-last-directory-history t
      ido-max-work-directory-list 30
      ido-max-work-file-list 50
      ido-max-prospects 8
      ido-confirm-unique-completion nil
      ido-create-new-buffer 'always
      ido-use-virtual-buffers t)
(add-hook 'lightemacs-after-init-hook #'ido-mode)

;;; DISABLED: Simple Commit message

;; ;; TODO make a plugin
;;
;; (defgroup custom-git-commit nil
;;   "Custom mode for Git commit messages."
;;   :group 'text)
;;
;; (defvar custom-git-commit-font-lock-keywords
;;   '(;; Highlight comments generated by Git
;;     ("^#.*$" . font-lock-comment-face)
;;     ;; Highlight standard Git footers
;;     ("^\\(Signed-off-by:\\|Co-authored-by:\\|Acked-by:\\|Tested-by:\\|Reviewed-by:\\|Fixes:\\|Closes:\\|Resolves:\\)"
;;      (1 font-lock-keyword-face))
;;     ;; Highlight issue tracker tickets (e.g., [PROJ-123])
;;     ("\\[[A-Z]+-[0-9]+\\]" . font-lock-type-face)
;;     ;; Highlight file paths in the status output within comments
;;     ("^#[[:space:]]+\\(modified\\|new file\\|deleted\\):[[:space:]]+\\(.*\\)$"
;;      (1 font-lock-builtin-face t)
;;      (2 font-lock-variable-name-face t)))
;;   "Font lock definitions for `custom-git-commit-mode'.")
;;
;; (defun custom-git-commit-setup ()
;;   "Set up variables and settings for the commit buffer."
;;   (setq fill-column 72)
;;   (turn-on-auto-fill))
;;
;; ;;;###autoload
;; (define-derived-mode custom-git-commit-mode text-mode "Git Commit"
;;   "Major mode for editing Git commit messages."
;;   (setq font-lock-defaults '(custom-git-commit-font-lock-keywords t))
;;   (custom-git-commit-setup))
;;
;; ;;;###autoload
;; (add-to-list 'auto-mode-alist '("COMMIT_EDITMSG\\'" . custom-git-commit-mode))
;; (add-to-list 'auto-mode-alist '("/git-rebase-todo\\'" . custom-git-commit-mode))

;;; Better commit message 2

;; (defgroup custom-git-commit nil
;;   "Custom mode for Git commit messages."
;;   :group 'text)
;;
;; (defvar custom-git-commit-font-lock-keywords
;;   '(;; Highlight diff additions and deletions
;;     ("^\\+.*$" (0 font-lock-string-face t))
;;     ("^-.*$" (0 font-lock-warning-face t))
;;     ;; Highlight diff headers
;;     ("^diff --git .*$" (0 font-lock-type-face t))
;;     ("^index [0-9a-f]+\\.\\.[0-9a-f]+.*$" (0 font-lock-comment-face t))
;;     ("^--- .*$" (0 font-lock-warning-face t))
;;     ("^\\+\\+\\+ .*$" (0 font-lock-string-face t))
;;     ;; Highlight diff hunk headers
;;     ("^@@ -[0-9]+\\(,[0-9]+\\)? \\+[0-9]+\\(,[0-9]+\\)? @@.*$" (0 font-lock-keyword-face t))
;;     ;; Highlight comments generated by Git
;;     ("^#.*$" (0 font-lock-comment-face t))
;;     ;; Highlight file paths in the status output within comments
;;     ("^#[[:space:]]+\\(modified\\|new file\\|deleted\\):[[:space:]]+\\(.*\\)$"
;;      (1 font-lock-builtin-face t)
;;      (2 font-lock-variable-name-face t))
;;     ;; Highlight standard Git footers
;;     ("^\\(Signed-off-by:\\|Co-authored-by:\\|Acked-by:\\|Tested-by:\\|Reviewed-by:\\|Fixes:\\|Closes:\\|Resolves:\\)"
;;      (1 font-lock-keyword-face))
;;     ;; Highlight issue tracker tickets (e.g., [PROJ-123])
;;     ("\\[[A-Z]+-[0-9]+\\]" . font-lock-type-face))
;;   "Font lock definitions for `custom-git-commit-mode'.")
;;
;; (defun custom-git-commit-setup ()
;;   "Set up variables and settings for the commit buffer."
;;   (setq fill-column 72)
;;   (turn-on-auto-fill))
;;
;; ;;;###autoload
;; (define-derived-mode custom-git-commit-mode text-mode "Git Commit"
;;   "Major mode for editing Git commit messages."
;;   (setq font-lock-defaults '(custom-git-commit-font-lock-keywords t))
;;   (custom-git-commit-setup))
;;
;; ;;;###autoload
;; (add-to-list 'auto-mode-alist '("COMMIT_EDITMSG\\'" . custom-git-commit-mode))
;; (add-to-list 'auto-mode-alist '("/git-rebase-todo\\'" . custom-git-commit-mode))

;;; Better commit message 3

(defgroup custom-git-commit nil
  "Custom mode for Git commit messages."
  :group 'text)

(defvar custom-git-commit-font-lock-keywords
  '(;; Highlight diff additions and deletions
    ("^\\+.*$" (0 font-lock-string-face t))
    ("^-.*$" (0 font-lock-warning-face t))
    ;; Highlight diff headers
    ("^diff --git .*$" (0 font-lock-type-face t))
    ("^index [0-9a-f]+\\.\\.[0-9a-f]+.*$" (0 font-lock-comment-face t))
    ("^--- .*$" (0 font-lock-warning-face t))
    ("^\\+\\+\\+ .*$" (0 font-lock-string-face t))
    ;; Highlight diff hunk headers
    ("^@@ -[0-9]+\\(,[0-9]+\\)? \\+[0-9]+\\(,[0-9]+\\)? @@.*$" (0 font-lock-keyword-face t))
    ;; Highlight diff context (unchanged lines)
    ("^[ \t\240].*$" (0 font-lock-comment-face t))
    ;; Highlight comments generated by Git
    ("^#.*$" (0 font-lock-comment-face t))
    ;; Highlight file paths in the status output within comments
    ("^#[[:space:]]+\\(modified\\|new file\\|deleted\\):[[:space:]]+\\(.*\\)$"
     (1 font-lock-builtin-face t)
     (2 font-lock-variable-name-face t))
    ;; Highlight standard Git footers
    ("^\\(Signed-off-by:\\|Co-authored-by:\\|Acked-by:\\|Tested-by:\\|Reviewed-by:\\|Fixes:\\|Closes:\\|Resolves:\\)"
     (1 font-lock-keyword-face))
    ;; Highlight issue tracker tickets (e.g., [PROJ-123])
    ("\\[[A-Z]+-[0-9]+\\]" . font-lock-type-face))
  "Font lock definitions for `custom-git-commit-mode'.")

(defun custom-git-commit-setup ()
  "Set up variables and settings for the commit buffer."
  (setq fill-column 72)
  (turn-on-auto-fill))

;;;###autoload
(define-derived-mode custom-git-commit-mode text-mode "Git Commit"
  "Major mode for editing Git commit messages."
  (setq font-lock-defaults '(custom-git-commit-font-lock-keywords t))
  (custom-git-commit-setup))

;;;###autoload
(add-to-list 'auto-mode-alist '("COMMIT_EDITMSG\\'" . custom-git-commit-mode))
(add-to-list 'auto-mode-alist '("/git-rebase-todo\\'" . custom-git-commit-mode))

;;; config.el ends here
