;;; config.el --- config -*- no-byte-compile: t; lexical-binding: t -*-

;; Author: James Cherti
;; URL: https://github.com/jamescherti/jc-dev
;;
;; Distributed under terms of the MIT license.
;;
;; Copyright (C) 2004-2026 James Cherti
;;
;; Permission is hereby granted, free of charge, to any person obtaining a copy
;; of this software and associated documentation files (the “Software”), to deal
;; in the Software without restriction, including without limitation the rights
;; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
;; copies of the Software, and to permit persons to whom the Software is
;; furnished to do so, subject to the following conditions:
;;
;; The above copyright notice and this permission notice shall be included in all
;; copies or substantial portions of the Software.
;;
;; THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
;; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;; SOFTWARE.

;;; Commentary:

;;; Code:

;;; External config

(load (expand-file-name "~/.config.el") :no-error :no-message :nosuffix)

;;; Optimization

(setq minimal-emacs-inhibit-message-during-startup t)
(setq minimal-emacs-inhibit-redisplay-during-startup t)

(setq site-run-file nil)
(setq inhibit-default-init t)

;; TODO remove from devemacs and my emacs and add this to lightemacs
(with-eval-after-load 'cus-edit
  ;; Prevent Emacs from writing custom settings to any file
  (advice-add 'custom-save-all :override #'ignore))

;;; Native-compilation

(setq enable-dir-local-variables t)
(setq enable-local-variables :safe)

(setq native-comp-jit-compilation t)
(setq native-comp-deferred-compilation t)
(setq package-native-compile t)

;;; Config

;; (setq lightemacs-theme-default-font "Iosevka Medium")
;; (setq lightemacs-theme-default-font "Iosevka SemiBold")
(setq lightemacs-theme-default-font "Iosevka Term SemiBold")

(setq lightemacs-load-compiled-init-files t)
(setq lightemacs-saveplace-recenter-after-find-file t)

(setq minimal-emacs-frame-title-format "Devemacs")

(setq lightemacs-dired-omit-parent-directory t)
(setq lightemacs-cycle nil)
(setq lightemacs-theme-name 'tomorrow-night-deepblue)
(setq lightemacs-theme-package 'tomorrow-night-deepblue-theme)

(setq lightemacs-modules '(le-flavor-micro
                           le-pathaction
                           le-markdown-mode
                           le-group-evil
                           le-persist-text-scale
                           le-xclip

                           le-compile-angel

                           ;; le-org
                           ;; le-consult
                           ;; le-vertico
                           ;; le-autorevert
                           ;; le-undo-fu
                           ;; le-undo-fu-session

                           ;; le-consult-dir
                           ;; le-embark-consult
                           ;; le-embark
                           ;; le-wgrep
                           ;; le-orderless

                           ;; le-evil-visualstar
                           ;; le-git-modes
                           ))

;;; DISABLED: Better commit message 3

;; BUG: This colors lists (-)

;; (defgroup custom-git-commit nil
;;   "Custom mode for Git commit messages."
;;   :group 'text)
;;
;; (defvar custom-git-commit-font-lock-keywords
;;   '(;; Highlight diff additions and deletions
;;     ("^\\+.*$" (0 font-lock-string-face t))
;;     ("^-.*$" (0 font-lock-warning-face t))
;;     ;; Highlight diff headers
;;     ("^diff --git .*$" (0 font-lock-type-face t))
;;     ("^index [0-9a-f]+\\.\\.[0-9a-f]+.*$" (0 font-lock-comment-face t))
;;     ("^--- .*$" (0 font-lock-warning-face t))
;;     ("^\\+\\+\\+ .*$" (0 font-lock-string-face t))
;;     ;; Highlight diff hunk headers
;;     ("^@@ -[0-9]+\\(,[0-9]+\\)? \\+[0-9]+\\(,[0-9]+\\)? @@.*$" (0 font-lock-keyword-face t))
;;     ;; Highlight diff context (unchanged lines)
;;     ("^[ \t\240].*$" (0 font-lock-comment-face t))
;;     ;; Highlight comments generated by Git
;;     ("^#.*$" (0 font-lock-comment-face t))
;;     ;; Highlight file paths in the status output within comments
;;     ("^#[[:space:]]+\\(modified\\|new file\\|deleted\\):[[:space:]]+\\(.*\\)$"
;;      (1 font-lock-builtin-face t)
;;      (2 font-lock-variable-name-face t))
;;     ;; Highlight standard Git footers
;;     ("^\\(Signed-off-by:\\|Co-authored-by:\\|Acked-by:\\|Tested-by:\\|Reviewed-by:\\|Fixes:\\|Closes:\\|Resolves:\\)"
;;      (1 font-lock-keyword-face))
;;     ;; Highlight issue tracker tickets (e.g., [PROJ-123])
;;     ("\\[[A-Z]+-[0-9]+\\]" . font-lock-type-face))
;;   "Font lock definitions for `custom-git-commit-mode'.")
;;
;; (defun custom-git-commit-setup ()
;;   "Set up variables and settings for the commit buffer."
;;   (setq fill-column 72)
;;   (turn-on-auto-fill))
;;
;; ;;;###autoload
;; (define-derived-mode custom-git-commit-mode text-mode "Git Commit"
;;   "Major mode for editing Git commit messages."
;;   (setq font-lock-defaults '(custom-git-commit-font-lock-keywords t))
;;   (custom-git-commit-setup))
;;
;; ;;;###autoload
;; (add-to-list 'auto-mode-alist '("COMMIT_EDITMSG\\'" . custom-git-commit-mode))
;; (add-to-list 'auto-mode-alist '("/git-rebase-todo\\'" . custom-git-commit-mode))

;;; Fido Vertical Mode

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; FIDO-VERTICAL-MODE
;;
;; fido-vertical-mode merges the behavior of fido-mode with the top-to-bottom
;; layout of icomplete-vertical-mode. It provides an Ido-like experience while
;; utilizing the modern standard completion infrastructure.
;;
;; Key features:
;; - Vertical layout: Candidates are displayed in a stacked, vertical list.
;; - Flex matching: Prioritizes the 'flex' completion style by default,
;;   matching non-adjacent characters.
;; - Ido keybindings: Rebinds minibuffer keys to match Ido habits (e.g., C-s
;;   and C-r cycle the list, RET selects the highlighted candidate).
;; - Directory shadowing: Typing ~/ or / during file completion immediately
;;   shadows the existing path to jump to home or root directories.
;;
;; Note: Because this mode is built directly on top of icomplete, all
;; icomplete-* variables remain active and necessary to control how candidates
;; are delayed, computed, and scrolled.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Good
(setq completion-auto-select nil  ; Alternative: 'second-tab
      completions-detailed t
      completions-group t
      completions-group-sort 'alphabetical)

;; Fido and Fido Vertical Mode are built directly on top of icomplete.
(setq
 ;; Good
 completion-ignore-case t
 read-buffer-completion-ignore-case t
 read-file-name-completion-ignore-case t
 icomplete-show-matches-on-no-input t
 icomplete-hide-common-prefix nil
 icomplete-compute-delay 0 ; value 0.01 for minimal-emacs.d TODO
 icomplete-scroll t

 ;; This removes the verbose "X possible completions:" text from the top of the
 ;; *Completions* buffer, saving vertical space.
 completions-header-format ""

 ;; This is highly recommended. Instead of strict alphabetical sorting, it sorts
 ;; candidates based on your minibuffer history, placing recently used files or
 ;; commands at the top.
 completions-sort 'historical

 ;; These are newer Emacs features that ensure the *Completions* buffer updates
 ;; dynamically and immediately as you type.
 completion-eager-display 'auto
 completion-eager-update 'auto

 ;; Good?
 icomplete-separator "\n"
 icomplete-delay-completions-threshold 0
 icomplete-prospects-height 10
 icomplete-with-completion-tables t
 icomplete-max-delay-chars 0
 icomplete-tidy-shadowed-file-names t
 icomplete-in-buffer t)

(setq ;; completion-styles '(partial-completion flex initials)
 completion-styles '(basic substring partial-completion flex)
 ;; Ignore case in file and buffer completions
 completions-format 'horizontal
 completions-max-height 20
 completion-show-help nil
 completion-show-inline-help nil)

(add-hook 'lightemacs-after-init-hook #'fido-vertical-mode)

;;; Modes that are disabled by default

;; TODO This is a duplicate mode. Move it to lightemacs in le-no-bloat.el

;; Force the unimpaired mode off globally
(setq lightemacs-evil-collection-inhibit-unimpaired-mode t)

;; Minibuffer-nonselected-mode: This mode highlights the minibuffer contents
;; using the minibuffer-nonselected face when an active minibuffer (such as a
;; recursive prompt or a background process) remains active after focus has
;; shifted to a different window.
;;
;; Utility: This feature is primarily intended for users who frequently utilize
;; recursive minibuffers. If your workflow seldom involves recursive editing,
;; the mode may offer limited benefit. If the visual feedback triggered by
;; window switching causes distractions or conflicts with your chosen theme, it
;; can be disabled safely without impacting core functionality.
(when (bound-and-true-p minibuffer-nonselected-mode)
  (minibuffer-nonselected-mode -1))
(setq-default minibuffer-nonselected-mode nil)

(when (bound-and-true-p global-eldoc-mode)
  (global-eldoc-mode -1))
(setq-default global-eldoc-mode nil)

(when (bound-and-true-p show-paren-mode)
  (show-paren-mode -1))
(setq-default show-paren-mode nil)

;; Disable Remote File Checks if Not Needed
(setq-default tramp-mode nil)
(when (bound-and-true-p windmove-mode)
  (windmove-mode -1))
(setq-default windmove-mode nil)

;; GPM mouse support is strictly for TTY consoles.
(when (bound-and-true-p gpm-mouse-mode)
  (gpm-mouse-mode -1))
(setq-default gpm-mouse-mode nil)

;; Useless for Evil users: This mode modifies minibuffer syntax tables for regex
;; navigation. Since Evil provides its own regex tools and operators that
;; operate independently of these minibuffer-specific highlighting side-effects,
;; this mode is redundant and can interfere with custom Evil keybindings.
(when (bound-and-true-p minibuffer-regexp-mode)
  (minibuffer-regexp-mode -1))
(setq-default minibuffer-regexp-mode nil)

;; In standard (vanilla) Emacs, you do not select text by shifting into a visual
;; mode. Instead, you drop an anchor called the "mark" by pressing C-SPC, and
;; then move your cursor. The text between the mark and your cursor becomes your
;; active selection.
;;
;; By default, Emacs uses `transient-mark-mode' to highlight this selection
;; visually, making it look like a standard modern text editor.
;;
;; If you use Evil (Vim bindings), this native highlighting gets in the way.
;; Evil handles text selection through its own Visual states (v, V, C-v). If
;; Emacs is also trying to highlight text in the background based on where your
;; last mark was dropped, the two systems create conflicting visual noise.
;;
;; Disabling `transient-mark-mode' stops Emacs from painting the screen with
;; highlights. Pressing C-SPC goes back to being a silent utility: it just drops
;; an invisible location bookmark that you can jump back to later, while you
;; leave all the actual visual text selection to Evil.
(with-eval-after-load 'simple
  (when (bound-and-true-p transient-mark-mode)
    (transient-mark-mode -1))
  (setq-default transient-mark-mode nil))


;;; DISABLED: Simple Commit message

;; ;; TODO make a plugin

(defgroup custom-git-commit nil
  "Custom mode for Git commit messages."
  :group 'text)

(defvar custom-git-commit-font-lock-keywords
  '(;; Highlight comments generated by Git
    ("^#.*$" . font-lock-comment-face)
    ;; Highlight standard Git footers
    ("^\\(Signed-off-by:\\|Co-authored-by:\\|Acked-by:\\|Tested-by:\\|Reviewed-by:\\|Fixes:\\|Closes:\\|Resolves:\\)"
     (1 font-lock-keyword-face))
    ;; Highlight issue tracker tickets (e.g., [PROJ-123])
    ("\\[[A-Z]+-[0-9]+\\]" . font-lock-type-face)
    ;; Highlight file paths in the status output within comments
    ("^#[[:space:]]+\\(modified\\|new file\\|deleted\\):[[:space:]]+\\(.*\\)$"
     (1 font-lock-builtin-face t)
     (2 font-lock-variable-name-face t)))
  "Font lock definitions for `custom-git-commit-mode'.")

(defun custom-git-commit-setup ()
  "Set up variables and settings for the commit buffer."
  (setq fill-column 72)
  (turn-on-auto-fill))

;;;###autoload
(define-derived-mode custom-git-commit-mode text-mode "Git Commit"
  "Major mode for editing Git commit messages."
  (setq font-lock-defaults '(custom-git-commit-font-lock-keywords t))
  (custom-git-commit-setup))

;;;###autoload
(add-to-list 'auto-mode-alist '("COMMIT_EDITMSG\\'" . custom-git-commit-mode))
(add-to-list 'auto-mode-alist '("/git-rebase-todo\\'" . custom-git-commit-mode))

;;; DISABLED: Better commit message 2

;; (defgroup custom-git-commit nil
;;   "Custom mode for Git commit messages."
;;   :group 'text)
;;
;; (defvar custom-git-commit-font-lock-keywords
;;   '(;; Highlight diff additions and deletions
;;     ("^\\+.*$" (0 font-lock-string-face t))
;;     ("^-.*$" (0 font-lock-warning-face t))
;;     ;; Highlight diff headers
;;     ("^diff --git .*$" (0 font-lock-type-face t))
;;     ("^index [0-9a-f]+\\.\\.[0-9a-f]+.*$" (0 font-lock-comment-face t))
;;     ("^--- .*$" (0 font-lock-warning-face t))
;;     ("^\\+\\+\\+ .*$" (0 font-lock-string-face t))
;;     ;; Highlight diff hunk headers
;;     ("^@@ -[0-9]+\\(,[0-9]+\\)? \\+[0-9]+\\(,[0-9]+\\)? @@.*$" (0 font-lock-keyword-face t))
;;     ;; Highlight comments generated by Git
;;     ("^#.*$" (0 font-lock-comment-face t))
;;     ;; Highlight file paths in the status output within comments
;;     ("^#[[:space:]]+\\(modified\\|new file\\|deleted\\):[[:space:]]+\\(.*\\)$"
;;      (1 font-lock-builtin-face t)
;;      (2 font-lock-variable-name-face t))
;;     ;; Highlight standard Git footers
;;     ("^\\(Signed-off-by:\\|Co-authored-by:\\|Acked-by:\\|Tested-by:\\|Reviewed-by:\\|Fixes:\\|Closes:\\|Resolves:\\)"
;;      (1 font-lock-keyword-face))
;;     ;; Highlight issue tracker tickets (e.g., [PROJ-123])
;;     ("\\[[A-Z]+-[0-9]+\\]" . font-lock-type-face))
;;   "Font lock definitions for `custom-git-commit-mode'.")
;;
;; (defun custom-git-commit-setup ()
;;   "Set up variables and settings for the commit buffer."
;;   (setq fill-column 72)
;;   (turn-on-auto-fill))
;;
;; ;;;###autoload
;; (define-derived-mode custom-git-commit-mode text-mode "Git Commit"
;;   "Major mode for editing Git commit messages."
;;   (setq font-lock-defaults '(custom-git-commit-font-lock-keywords t))
;;   (custom-git-commit-setup))
;;
;; ;;;###autoload
;; (add-to-list 'auto-mode-alist '("COMMIT_EDITMSG\\'" . custom-git-commit-mode))
;; (add-to-list 'auto-mode-alist '("/git-rebase-todo\\'" . custom-git-commit-mode))

;;; config.el ends here
