((nil . ((env-allow-syntax-checkers . t)
         (env-allow-syntax-checker-package-lint . nil)
         (env-allow-lsp . t)
         (env-allow-whitespace-cleanup . t)
         (env-allow-language-servers . t)
         (env-allow-reformatters . t))))
