#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -e
set -u

ATEXIT_DONE=0
atexit() {
  local errno="$?"
  if [[ "$ATEXIT_DONE" -eq 0 ]]; then
    disable_screensaver false
    ATEXIT_DONE=1
  fi
  exit "$errno"
}

is_gnome() {
  [[ "$XDG_CURRENT_DESKTOP" = GNOME ]] && return 0
  return 1
}

is_xfce() {
  [[ "$XDG_CURRENT_DESKTOP" = "XFCE" ]] && return 0
  return 1
}

gnome_disable_screensaver() {
  if [[ $1 = true ]]; then
    gsettings set org.gnome.desktop.session idle-delay 0
    gsettings set org.gnome.desktop.screensaver lock-enabled false
    gsettings set org.gnome.desktop.screensaver idle-activation-enabled false
  else
    gsettings set org.gnome.desktop.session idle-delay "$GNOME_IDLE_DELAY"
    gsettings set org.gnome.desktop.screensaver lock-enabled "$GNOME_LOCK_ENABLED"
    gsettings set org.gnome.desktop.screensaver idle-activation-enabled "$GNOME_IDLE_ACTIVATION_ENABLED"
  fi

  echo "[Gnome idle delay] $(gsettings get org.gnome.desktop.session idle-delay)"
  echo "[Gnome lock] $(gsettings get org.gnome.desktop.screensaver lock-enabled)"
  echo "[Gnome idle activation enabled] $(gsettings get org.gnome.desktop.screensaver idle-activation-enabled)"
}

xfce_disable_screensaver() {
  if which xfconf-query >/dev/null 2>&1; then
    xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/presentation-mode --set "$1"
    return "$?"
  fi
  return 1
}

disable_screensaver() {
  if [[ $1 != true ]] && [[ $1 != false ]]; then
    echo "Error: disable_screensaver <true|false>"
    exit 1
  fi

  if is_gnome; then
    gnome_disable_screensaver "$1"
  elif is_xfce; then
    xfce_disable_screensaver "$1"
  fi

  if [[ $1 = true ]]; then
    echo "[INFO] Screensaver disabled."
  else
    echo "[INFO] Screensaver enabled."
  fi
}

init() {
  trap 'atexit' INT TERM EXIT
  if is_gnome; then
    GNOME_IDLE_DELAY=$(gsettings get org.gnome.desktop.session idle-delay)
    GNOME_LOCK_ENABLED="$(gsettings get org.gnome.desktop.screensaver lock-enabled)"
    GNOME_IDLE_ACTIVATION_ENABLED="$(gsettings get org.gnome.desktop.screensaver idle-activation-enabled)"

    DETECTED_SCREENSAVER=gnome
  elif is_xfce; then
    DETECTED_SCREENSAVER=xfce
  else
    echo "[ERROR] The screensaver was not detected." >&2
    exit 1
  fi

  echo "[INFO] Detected screensaver: $DETECTED_SCREENSAVER"
  echo
}

main() {
  if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <duration>" >&2
    return 1
  fi

  init
  disable_screensaver true

  echo "[WAIT] $1"
  sleep "$1"

  disable_screensaver false

  return 0
}

main "$@" || exit "$?"
