#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# easyddc: A wrapper for ddcutil to manage external displays.
#
# List monitors:
# ddcutil detect | grep -E "I2C bus:|Model:|Serial number:"
#
# ddcutil capabilities | grep -A 10 "Feature: 14"

VCP_BRIGHTNESS="10"
VCP_CONTRAST="12"
VCP_COLOR_PRESET="14"
VCP_INPUT="60"
TARGET_MONITOR=""

if [[ -f ~/.easyddc ]]; then
  # shellcheck disable=SC1090
  source ~/.easyddc
fi

show_help() {
  echo "Usage: monitor-ctl [options]"
  echo "Options:"
  echo "  -m ID       Specify monitor (e.g., bus number, serial, or model)"
  echo "  -b VALUE    Set brightness (0-100)"
  echo "  -c VALUE    Set contrast (0-100)"
  echo "  -p VALUE    Set color preset"
  echo "  -i VALUE    Set input source"
  echo "  -g VCP      Get current value for a VCP code"
  echo "  -h          Show this help menu"
}

# Detect active I2C buses if no specific monitor is targeted
get_buses() {
  ddcutil detect | grep "I2C bus:" | awk -F'-' '{print $NF}'
}

execute_ddcutil() {
  local action=$1
  local vcp=$2
  local value=$3

  # If you know your monitor is always on bus 4, hardcode it or pass it as -m 4
  if [[ "$TARGET_MONITOR" =~ ^[0-9]+$ ]]; then
    # Direct bus access is the fastest possible command
    ddcutil --bus "$TARGET_MONITOR" "$action" "$vcp" "$value" --noverify
  else
    # Only if no bus is provided, we perform the slow search
    local buses
    buses=$(get_buses)
    for bus in $buses; do
      ddcutil --bus "$bus" "$action" "$vcp" "$value" --noverify
    done
  fi
}

while getopts "m:b:c:p:i:g:h" opt; do
  case "$opt" in
  m) TARGET_MONITOR="$OPTARG" ;;
  b) execute_ddcutil "setvcp" "$VCP_BRIGHTNESS" "$OPTARG" ;;
  c) execute_ddcutil "setvcp" "$VCP_CONTRAST" "$OPTARG" ;;
  p) execute_ddcutil "setvcp" "$VCP_COLOR_PRESET" "$OPTARG" ;;
  i) execute_ddcutil "setvcp" "$VCP_INPUT" "$OPTARG" ;;
  g) execute_ddcutil "getvcp" "$OPTARG" ;;
  h)
    show_help
    exit 0
    ;;
  *)
    show_help
    exit 1
    ;;
  esac
done

if [ $# -eq 0 ]; then
  show_help
fi
