#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

set -euf -o pipefail

EMACS_EDIT_TIMEOUT="${EMACS_EDIT_TIMEOUT:-3}"
# EMACS_EDIT_NEW_TAB="${EMACS_EDIT_NEW_TAB:-1}"
EMACS_EDIT_NEW_TAB=1
EMACS_EDIT_WAIT_SECONDS=30
EMACS_EDIT_EMACS_BIN=run-emacs

run_emacsclient() {
  emacsclient --no-wait "--timeout=$EMACS_EDIT_TIMEOUT" "$@" 2>/dev/null \
    || return "$?"
}

emacs_open_file() {
  if [[ "$EMACS_EDIT_NEW_TAB" != "0" ]]; then
    run_emacsclient --suppress-output \
      --eval '(let ((inhibit-redisplay t)) (tab-bar-new-tab) (delete-other-windows))' || :
  fi

  run_emacsclient --suppress-output "$@" || :
}

is_emacs_server_running() {
  # Hide output; return 0 if successful, 1 if connection fails
  emacsclient -e "(+ 1 1)" &>/dev/null
}

load_easysession_session() {
  local wait_cycles=0
  local max_cycles=$((EMACS_EDIT_WAIT_SECONDS * 10))
  local SESSION_LOADED

  while true; do
    if [[ "$wait_cycles" -ge "$max_cycles" ]]; then
      echo "Error: Timeout waiting for EasySession to load." >&2
      exit 1
    fi

    SESSION_LOADED=$(
      run_emacsclient \
        -e "(and (boundp 'easysession--current-session-name)
                 easysession--current-session-name)" 2>/dev/null || :
    )

    if [[ "$SESSION_LOADED" != "" ]] \
      && [[ "$SESSION_LOADED" != "nil" ]] \
      && [[ "$SESSION_LOADED" != '"nil"' ]]; then
      break
    fi

    sleep 0.1
    wait_cycles=$((wait_cycles + 1))
  done
}

main() {
  # Requirements
  for CMD in "$EMACS_EDIT_EMACS_BIN" emacsclient; do
    if ! type -P "$CMD" &>/dev/null; then
      echo "Error: $CMD not found in \$PATH" >&2
      exit 1
    fi
  done

  # Edit
  xdevenv-emacs &>/dev/null &
  disown

  if is_emacs_server_running; then
    load_easysession_session
    emacs_open_file "$@" || :
    # run_emacsclient "$@" || :
  else
    local wait_cycles=0
    local max_cycles=$((EMACS_EDIT_WAIT_SECONDS * 10))
    local after_emacs_init

    # Wait for Emacs standard initialization
    while true; do
      if [[ "$wait_cycles" -ge "$max_cycles" ]]; then
        echo "Error: Timeout waiting for Emacs core to initialize." >&2
        exit 1
      fi

      after_emacs_init=$(run_emacsclient -e "(when after-init-time t)" || :)
      # Check for both literal t and quoted "t"
      if [[ "$after_emacs_init" == "t" ]] \
        || [[ "$after_emacs_init" == '"t"' ]]; then
        break
      fi
      sleep 0.1
      wait_cycles=$((wait_cycles + 1))
    done

    # EasySession: Wait until the session is loaded
    load_easysession_session

    # Open the file in a new tab
    emacs_open_file "$@" || :
  fi
}

main "$@"
