#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#
#

set -u
set -e

cleanup-emacs-files() {
  while IFS= read -r dir; do
    if [[ -d "$dir" ]]; then
      if [[ $1 != dry-run ]]; then
        echo "[CLEANUP] Delete .elc and .eln files: $dir"
      fi

      local opts=()
      if [[ $1 != dry-run ]]; then
        opts=("-delete")
      fi
      find "$dir" \( -iname '*.elc' -o -iname '*.eln' \) "${opts[@]}"
    fi
  done < <(
    if [[ -d "$HOME/src" ]]; then
      echo "$HOME/src"
    fi

    find ~ -maxdepth 1 -name '.*emacs*.d'
  )
}

cleanup-emacs-files dry-run

echo
read -r -p "Delete all compiled .elc and .eln files? [y,n] " ANSWER
if [[ "$ANSWER" != "y" ]]; then
  exit 1
fi
echo

cleanup-emacs-files apply
