#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#
#

set -u
set -e

# Cache the availability of fd to avoid redundant checks inside the loop
if command -v fd >/dev/null 2>&1; then
  HAS_FD=true
else
  HAS_FD=false
fi

cleanup-emacs-files() {
  while IFS= read -r dir; do
    if [[ -d "$dir" ]]; then
      if [[ $1 != dry-run ]]; then
        echo "[CLEANUP] Delete .elc and .eln files: $dir"
      fi

      if [[ "$HAS_FD" == true ]]; then
        local fd_opts=()
        if [[ $1 != dry-run ]]; then
          fd_opts=("--exec-batch" "rm" "-f")
        fi
        # The . character is passed to serve as a catch-all regular expression
        # pattern. This ensures that fd correctly interprets the next argument,
        # "$dir", as the target directory path rather than the search pattern.
        fd --type f --hidden --no-ignore --ignore-case \
          --extension elc --extension eln --color=never \
          . "$dir" "${fd_opts[@]}"
      else
        local find_opts=()
        if [[ $1 != dry-run ]]; then
          find_opts=("-delete")
        fi
        find "$dir" -type f \( -iname '*.elc' -o -iname '*.eln' \) \
          "${find_opts[@]}"
      fi
    fi
  done < <(
    if [[ -d "$HOME/src" ]]; then
      echo "$HOME/src"
    fi

    if [[ "$HAS_FD" == true ]]; then
      fd --type d --hidden --no-ignore --max-depth 1 --glob '.*emacs*.d' "$HOME"
    else
      find "$HOME" -maxdepth 1 -type d -name '.*emacs*.d'
    fi
  )
}

cleanup-emacs-files dry-run

echo
read -r -p "Delete all compiled .elc and .eln files? [y,n] " ANSWER
if [[ "$ANSWER" != "y" ]]; then
  exit 1
fi
echo

cleanup-emacs-files apply
