#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

set -euf -o pipefail

EMACS_EDIT_TIMEOUT="${EMACS_EDIT_TIMEOUT:-3}"
# EMACS_EDIT_NEW_TAB="${EMACS_EDIT_NEW_TAB:-1}"
EMACS_EDIT_NEW_TAB=1
EMACS_EDIT_WAIT_SECONDS=30
EMACS_EDIT_EMACS_BIN=run-emacs

run-emacsclient() {
  emacsclient --no-wait "--timeout=$EMACS_EDIT_TIMEOUT" "$@" 2>/dev/null \
    || return "$?"
}

emacs-open-file() {
  if [[ "$EMACS_EDIT_NEW_TAB" != "0" ]]; then
    run-emacsclient --suppress-output --eval '(tab-bar-new-tab)' || :
  fi

  run-emacsclient --suppress-output "$@" || :
}

is-emacs-server-running() {
  # Hide output; return 0 if successful, 1 if connection fails
  emacsclient -e "(+ 1 1)" &>/dev/null
}

main() {
  # Requirements
  for CMD in "$EMACS_EDIT_EMACS_BIN" emacsclient; do
    if ! type -P "$CMD" &>/dev/null; then
      echo "Error: $CMD not found in \$PATH" >&2
      exit 1
    fi
  done

  # Edit
  if is-emacs-server-running; then
    # EMACS_DAEMON=$(run-emacsclient -e '(daemonp)' || :)

    emacs-open-file "$@" || :
    # run-emacsclient "$@" || :
  else
    "$EMACS_EDIT_EMACS_BIN" &>/dev/null &
    disown

    wait_cycles=0
    max_cycles=$((EMACS_EDIT_WAIT_SECONDS * 10))

    # Wait for Emacs standard initialization
    while true; do
      if [[ "$wait_cycles" -ge "$max_cycles" ]]; then
        echo "Error: Timeout waiting for Emacs core to initialize." >&2
        exit 1
      fi

      AFTER_EMACS_INIT=$(run-emacsclient -e "(when after-init-time t)" || :)
      # Check for both literal t and quoted "t"
      if [[ "$AFTER_EMACS_INIT" == "t" ]] \
        || [[ "$AFTER_EMACS_INIT" == '"t"' ]]; then
        break
      fi
      sleep 0.1
      wait_cycles=$((wait_cycles + 1))
    done

    # EasySession: Wait until the session is loaded
    wait_cycles=0
    while true; do
      if [[ "$wait_cycles" -ge "$max_cycles" ]]; then
        echo "Error: Timeout waiting for EasySession to load." >&2
        exit 1
      fi

      SESSION_LOADED=$(
        run-emacsclient \
          -e "(and (boundp 'easysession--current-session-name)
                 easysession--current-session-name)" 2>/dev/null || :
      )

      if [[ "$SESSION_LOADED" != "" ]] \
        && [[ "$SESSION_LOADED" != "nil" ]] \
        && [[ "$SESSION_LOADED" != '"nil"' ]]; then
        break
      fi

      sleep 0.1
      wait_cycles=$((wait_cycles + 1))
    done

    # Open the file in a new tab
    emacs-open-file "$@" || :
  fi
}

main "$@"
