#!/usr/bin/env bash

set -e
set -u

if [ "$(id -u)" -ne "0" ]; then
  echo "Error: you need root privileges to run this script." >&2
  exit 1
fi

cd "$1"

echo "Prepare chroot: $(pwd)"
echo "Press enter..."
read -r -p "" _variable </dev/tty

for item in dev proc sys run; do
  ! mountpoint -q "$item" && mount -o bind "/$item" "$item"
done

chroot . /bin/bash -l
