#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

_find_dominating_file() {
  # Find a file in the current directory or in its parent directories (e.g.
  # ".gitignore")
  local filename="$1"
  local error=0

  pushd . >/dev/null 2>&1
  while true; do
    local previous_dir=""
    previous_dir="$(pwd)"
    local path_filename
    path_filename="$previous_dir/$filename"
    if [[ -f "$path_filename" ]]; then
      echo "$path_filename"
      break
    fi

    command cd .. || break

    local current_dir
    current_dir="$(pwd)"
    if [[ $current_dir = "$previous_dir" ]]; then
      error=1
      break
    fi
  done
  # shellcheck disable=SC2164
  popd >/dev/null 2>&1

  return "$error"
}

_find_dominating_file "$@"
