#!/usr/bin/env python
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

import subprocess
import sys


def check_tag_exists(tag):
    """Check if a Git tag exists."""
    try:
        result = subprocess.run(["git", "tag"],
                                capture_output=True,
                                text=True, check=True)
        tags = result.stdout.splitlines()
        return tag in tags
    except subprocess.CalledProcessError as err:
        print(f"Error checking tags: {err.stderr}")
        sys.exit(1)


def create_tag(tag):
    """Create a new Git tag."""
    try:
        subprocess.run(["git", "tag", "-s", tag, "-m", tag], check=True)
        print(f"Tag {tag} created successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error creating tag: {e.stderr}")
        sys.exit(1)


def push_tags():
    """Push all Git tags."""
    try:
        subprocess.run(["git", "push", "--tags"], check=True)
        print("Tag pushed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error pushing tags: {e.stderr}")
        sys.exit(1)


def ensure_tag_exists_in_codebase(tag):
    """Search for a tag in the current Git codebase."""
    try:
        result = subprocess.run(["git", "grep", "-n", tag],
                                capture_output=True, text=True, check=True)
        if result.stdout:
            return
    except subprocess.CalledProcessError as err:
        if err.returncode != 1:
            print(f"Error searching for tag '{tag}' in codebase: {err.stderr}")
            sys.exit(1)

    print(f"Error: The tag '{tag}' was not found in the codebase.")
    sys.exit(1)


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <tagname>")
        sys.exit(1)

    tag = sys.argv[1]

    if check_tag_exists(tag):
        print(f"Error: Tag {tag} already exists.")
        sys.exit(1)

    ensure_tag_exists_in_codebase(tag)
    create_tag(tag)
    # push_tags()


if __name__ == "__main__":
    main()
