#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -euf -o pipefail

# shellcheck disable=SC1090
GIT_PULLALL_SCRIPT=$(realpath "$0")
if ! [[ -f "$GIT_PULLALL_SCRIPT" ]]; then
  echo "$0: '$GIT_PULLALL_SCRIPT' was not found" >&2
  exit 1
fi

# Ensure the script is run from a Git repository root
if ! GIT_REPO=$(git rev-parse --show-toplevel 2>/dev/null); then
  echo "$0: Must be run from within a Git repository" >&2
  exit 1
fi

# git submodule --quiet foreach --recursive "$GIT_PULLALL_SCRIPT"
# echo "------------------------------------------------------------------"
# echo "[GIT PULLALL] $GIT_REPO"
# echo "------------------------------------------------------------------"

cmd=(git pull --ff-only)

if [[ -f "$GIT_REPO/.gitmodules" ]]; then
  esa ssh-add-exec git-psm "${cmd[@]}"
else
  esa ssh-add-exec "${cmd[@]}"
fi
