#!/usr/bin/env python
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

import subprocess
import sys


def check_tag_exists(tag):
    """Check if a Git tag exists."""
    try:
        result = subprocess.run(["git", "tag"],
                                capture_output=True,
                                text=True, check=True)
        tags = result.stdout.splitlines()
        return tag in tags
    except subprocess.CalledProcessError as err:
        print(f"Error checking tags: {err.stderr}")
        sys.exit(1)


def create_tag(tag):
    """Create a new Git tag."""
    try:
        subprocess.run(["git", "tag", "-s", tag, "-m", tag], check=True)
        print(f"Tag {tag} created successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error creating tag: {e.stderr}")
        sys.exit(1)


def push_tags():
    """Push all Git tags."""
    try:
        subprocess.run(["git", "push", "--tags"], check=True)
        print("Tag pushed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error pushing tags: {e.stderr}")
        sys.exit(1)


def ensure_tag_exists_in_codebase(tag):
    """Search for a tag in the current Git codebase."""
    try:
        result = subprocess.run(["git", "grep", "-n", tag],
                                capture_output=True, text=True, check=True)
        if result.stdout:
            return
    except subprocess.CalledProcessError as err:
        if err.returncode != 1:
            print(f"Error searching for tag '{tag}' in codebase: {err.stderr}")
            sys.exit(1)

    print(f"Error: The tag '{tag}' was not found in the codebase.")
    sys.exit(1)


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <tagname>")
        sys.exit(1)

    tag = sys.argv[1]

    if check_tag_exists(tag):
        print(f"Error: Tag {tag} already exists.")
        sys.exit(1)

    ensure_tag_exists_in_codebase(tag)
    create_tag(tag)
    # push_tags()


if __name__ == "__main__":
    main()
