#!/bin/bash
#
# Check GPG signatures of all Git commits.
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

set -uf -o pipefail
IFS=$'\n\t'

main() {
  local amount_commits=0
  local commit=""
  local error=0
  local list_commits=()

  readarray -t list_commits < <(git rev-list HEAD)
  if [[ ${#list_commits[@]} -eq 0 ]]; then
    echo
    echo "Error: no commits were found in the directory '$(pwd)'." >&2
    exit 1
  fi

  for commit in "${list_commits[@]}"; do
    if ! git verify-commit "$commit" >/dev/null 2>&1; then
      error=$((error + 1))
      break
    fi
    amount_commits=$((amount_commits + 1))
  done

  if [[ $error = 0 ]]; then
    echo "[SUCCESS] GPG signatures of all the commits are valid ($amount_commits commits)."
  else
    echo "[ERROR] Error with:"
    git show --show-signature "$commit"
    echo
    echo "[ERROR] Failed to validate the GPG signature of the commit: $commit" >&2
    exit 1
  fi

  exit 0
}

main "$@"
