#!/bin/bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Find the default branch (e.g., main or master)
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD \
  | sed 's@^refs/remotes/origin/@@')

# Check if develop branch exists locally
if git show-ref --verify --quiet refs/heads/develop; then
  # Check if develop is fully merged into the default branch
  if git merge-base --is-ancestor develop "$DEFAULT_BRANCH"; then
    echo "[CLEAN] 'develop' is fully merged into '$DEFAULT_BRANCH'."
    exit 0
  else
    echo "[UNMERGED] 'develop' has commits not in '$DEFAULT_BRANCH'."
    exit 0
  fi
else
  echo "[IGNORE] 'develop' branch does not exist."
  exit 0
fi
