#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

main() {
  # Ensure we have at least 3 arguments
  if [[ $# -lt 3 ]]; then
    echo "Usage: run_every <seconds> <reference_file> <command...>" >&2
    return 1
  fi

  local interval="$1"
  local lock_file="$2"
  shift 2
  local command=("$@")

  # Ensure the directory exists
  mkdir -p "$(dirname "$lock_file")"

  if [[ -f "$lock_file" ]]; then
    local current_time
    current_time=$(date +%s)
    local last_run
    last_run=$(stat -c %Y "$lock_file")
    local elapsed
    elapsed=$((current_time - last_run))

    if [[ $elapsed -ge $interval ]]; then
      "${command[@]}"
      touch "$lock_file"
    else
      echo "[IGNORED] $*"
    fi
  else
    # First time running: execute and create the file
    "${command[@]}"
    touch "$lock_file"
  fi

}

main "$@"
