#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

# Safely assign default values
RUN_EMACS_FORCE="${RUN_EMACS_FORCE:-0}"

EMACS_ARGS_DICT=(
  --no-site-file
  --no-site-lisp
  --no-splash
  --no-x-resources
  # Removed: --no-loadup
  # The --no-loadup option in GNU Emacs prevents Emacs from loading its standard
  # startup file loadup.el. This file normally initializes a large portion of
  # the core environment. Using this option therefore has significant side
  # effects.
  --no-loadup
)
EMACS_EDIT_TIMEOUT="${EMACS_EDIT_TIMEOUT:-3}"

# shellcheck disable=SC1090
# In case .profile or .bashrc modify the current directory
pushd . &>/dev/null

if [[ -f ~/.profile ]]; then
  # shellcheck disable=SC1090
  source ~/.profile &>/dev/null || true
fi

if [[ -f ~/.bashrc ]]; then
  # shellcheck disable=SC1090
  source ~/.bashrc &>/dev/null || true
fi

# In case .profile or .bashrc modify the current directory
popd &>/dev/null

set -euf -o pipefail

# Emacs: lsp-mode can be compiled in 2 modes plist and hash-table based
# lsp-use-plists flag. plists provide better performance in deserialization and
# also put less presure than hash-tables.
export LSP_USE_PLISTS=true

run-emacsclient-nowait() {
  emacsclient --no-wait "--timeout=$EMACS_EDIT_TIMEOUT" "$@" 2>/dev/null \
    || return "$?"
}

is-emacs-server-running() {
  # Hide output; return 0 if successful, 1 if connection fails
  emacsclient -e "(+ 1 1)" &>/dev/null
}

load_emacs_profile() {
  RUN_EMACS_BIN="${RUN_EMACS_BIN:-}"
  OSFAMILY=$(~/.local/bin/osid)
  EMACS_PROFILE="${EMACS_PROFILE:-}"
  # if ! [[ -f "$RUN_EMACS_BIN" ]] && [[ $OSFAMILY = arch ]]; then
  #   export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-master/bin/emacs"
  #   EMACS_D="$HOME/.emacs-master.d/"
  #   # export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-emacs-31/bin/emacs"
  # fi
  EMACS_D=""

  if ! [[ -f "$RUN_EMACS_BIN" ]]; then
    export RUN_EMACS_BIN="/usr/bin/emacs"
    EMACS_D="$HOME/.emacs-use-package.d/"
  fi

  if ! [[ -f "$RUN_EMACS_BIN" ]]; then
    export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-master/bin/emacs"
    EMACS_D="$HOME/.emacs-master.d/"
    # export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-emacs-31/bin/emacs"
  fi

  echo $RUN_EMACS_BIN
  echo $EMACS_D

  if ! [[ -f "$RUN_EMACS_BIN" ]]; then
    echo "Error: The Emacs binary does not exist: $RUN_EMACS_BIN" >&2
    exit 1
  fi

  # if [[ $EMACS_PROFILE != "" ]]; then
  #   EMACS_D="$HOME/.emacs-$EMACS_PROFILE.d/"
  # else
  #   if [[ $OSFAMILY = arch ]]; then
  #     # Emacs master
  #     EMACS_D="$HOME/.emacs-master.d/"
  #     # EMACS_D="$HOME/.emacs-straight.d/"
  #     # EMACS_D="$HOME/.emacs-elpaca.d/"
  #   else
  #     # Emacs 31
  #     EMACS_D="$HOME/.emacs-use-package.d/"
  #   fi
  # fi

  if [[ -f "$EMACS_D" ]]; then
    echo "Error: The Emacs user directory does not exist: $EMACS_D" >&2
    exit 1
  fi
  export EMACSNATIVELOADPATH="$EMACS_D/var/eln-cache/:"
  export RUN_EMACS_BIN
}

main() {
  load_emacs_profile

  EMACS_ARGS_DICT+=("--init-directory")
  EMACS_ARGS_DICT+=("$EMACS_D")

  if [[ $RUN_EMACS_BIN == "" ]]; then
    echo "Error: \$RUN_EMACS_BIN is not set or empty." >&2
    exit 1
  fi

  # Correctly check if the binary exists in the system PATH
  if ! RUN_EMACS_BIN=$(type -P "$RUN_EMACS_BIN" 2>/dev/null); then
    echo "Error: Command not found in PATH: '$RUN_EMACS_BIN'" >&2
    exit 1
  fi

  if [[ "${XDG_SESSION_TYPE:-}" = wayland ]]; then
    # By default, GTK applications try to guess the best backend to use. If you
    # want to guarantee that Emacs runs natively as a Wayland client and does
    # not fall back to XWayland, you should explicitly set the backend.
    export GDK_BACKEND=wayland

    # A common issue with the Emacs PGTK build involves input lag, freezing, or
    # swallowed keystrokes when typing or scrolling. This is often caused by
    # GTK's default input method module interfering with Emacs's internal event
    # loop. Disabling the GTK input module resolves most of these issues.
    #
    # https://github.com/emacs-mirror/emacs/blob/master/etc/PROBLEMS
    #
    # Emacs built with GTK lags in its response to keyboard input. This can
    # happen when input methods are used. It happens because Emacs behaves in an
    # unconventional way with respect to GTK input methods: it registers to
    # receive keyboard input as unprocessed key events with metadata (as opposed
    # to receiving them as text strings). Most GTK programs use the latter
    # approach, so some modern input methods have bugs and misbehave when faced
    # with the way Emacs does it.
    #
    # A workaround is to set GTK_IM_MODULE=none in the environment, or maybe
    # find a different input method without these problems.
    export GTK_IM_MODULE=none
    export XMODIFIERS=@im=none
    echo "[INFO] Change GDK_BACKEND to wayland and GTK_IM_MODULE to none"
  fi

  local emacs_dir
  emacs_dir=$(dirname "$RUN_EMACS_BIN")
  export PATH="$emacs_dir:$PATH"

  if [[ -d "$PWD" ]]; then
    EMACS_ARGS_DICT+=(--chdir "$PWD")
  fi

  if [[ "$RUN_EMACS_FORCE" -eq 0 ]] && is-emacs-server-running; then
    EMACS_DAEMON=$(run-emacsclient-nowait -e '(daemonp)' || :)

    if [[ $EMACS_DAEMON == "t" ]]; then
      emacsclient -c
    fi

    exit 0
  else
    echo "[RUN]" "$RUN_EMACS_BIN" "${EMACS_ARGS_DICT[@]}" "$@"
    exec "$RUN_EMACS_BIN" "${EMACS_ARGS_DICT[@]}" "$@"
    # exec jemacs "${EMACS_ARGS_DICT[@]}" "$@"
  fi
}

main "$@"
