#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Safely assign default values
RUN_EMACS_FORCE="${RUN_EMACS_FORCE:-0}"

EMACS_ARGS_DICT=(
  --no-site-file
  --no-site-lisp
  --no-splash
  --no-x-resources
  # Removed: --no-loadup
  # The --no-loadup option in GNU Emacs prevents Emacs from loading its standard
  # startup file loadup.el. This file normally initializes a large portion of
  # the core environment. Using this option therefore has significant side
  # effects.
  --no-loadup
)
EMACS_EDIT_TIMEOUT="${EMACS_EDIT_TIMEOUT:-3}"

# shellcheck disable=SC1090
# In case .profile or .bashrc modify the current directory
pushd . &>/dev/null

if [[ -f ~/.profile ]]; then
  # shellcheck disable=SC1090
  source ~/.profile &>/dev/null || true
fi

if [[ -f ~/.bashrc ]]; then
  # shellcheck disable=SC1090
  source ~/.bashrc &>/dev/null || true
fi

# In case .profile or .bashrc modify the current directory
popd &>/dev/null

set -euf -o pipefail

# Emacs: lsp-mode can be compiled in 2 modes plist and hash-table based
# lsp-use-plists flag. plists provide better performance in deserialization and
# also put less presure than hash-tables.
export LSP_USE_PLISTS=true

run-emacsclient-nowait() {
  emacsclient --no-wait "--timeout=$EMACS_EDIT_TIMEOUT" "$@" 2>/dev/null \
    || return "$?"
}

is-emacs-server-running() {
  # Hide output; return 0 if successful, 1 if connection fails
  emacsclient -e "(+ 1 1)" &>/dev/null
}

load_emacs_profile() {
  RUN_EMACS_BIN="${RUN_EMACS_BIN:-}"
  OSFAMILY=$(~/.local/bin/osid)
  if [[ $RUN_EMACS_BIN != "" ]]; then
    if [[ $OSFAMILY = arch ]]; then
      # Emacs master
      OSFAMILY=$(osid)
      export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-emacs-31/bin/emacs"
      EMACS_D="$HOME/.emacs-master.d/"
      export EMACSNATIVELOADPATH="$EMACS_D/var/eln-cache/:"
    else
      # Emacs 31
      export RUN_EMACS_BIN="/usr/bin/emacs"
      if ! [[ -f "$RUN_EMACS_BIN" ]]; then
        if [[ $OSFAMILY = arch ]]; then
          export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/tag-emacs-30.2/bin/emacs"
        else
          export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-emacs-30/bin/emacs"
        fi
      fi

      EMACS_D="$HOME/.emacs-use-package.d/"
      export EMACSNATIVELOADPATH="$EMACS_D/var/eln-cache/:"
    fi
  fi
}

main() {
  load_emacs_profile

  EMACS_ARGS_DICT+=("--init-directory")
  EMACS_ARGS_DICT+=("$EMACS_D")

  if [[ $RUN_EMACS_BIN == "" ]]; then
    echo "Error: \$RUN_EMACS_BIN is not set or empty." >&2
    exit 1
  fi

  # Correctly check if the binary exists in the system PATH
  if ! RUN_EMACS_BIN=$(type -P "$RUN_EMACS_BIN" 2>/dev/null); then
    echo "Error: Command not found in PATH: '$RUN_EMACS_BIN'" >&2
    exit 1
  fi

  if [[ "${XDG_SESSION_TYPE:-}" = wayland ]]; then
    # By default, GTK applications try to guess the best backend to use. If you
    # want to guarantee that Emacs runs natively as a Wayland client and does not
    # fall back to XWayland, you should explicitly set the backend.
    export GDK_BACKEND=wayland

    # A common issue with the Emacs PGTK build involves input lag, freezing, or
    # swallowed keystrokes when typing or scrolling. This is often caused by GTK's
    # default input method module interfering with Emacs's internal event loop.
    # Disabling the GTK input module resolves most of these issues.
    #
    # https://github.com/emacs-mirror/emacs/blob/master/etc/PROBLEMS
    #
    # Emacs built with GTK lags in its response to keyboard input. This can
    # happen when input methods are used. It happens because Emacs behaves in an
    # unconventional way with respect to GTK input methods: it registers to
    # receive keyboard input as unprocessed key events with metadata (as opposed
    # to receiving them as text strings). Most GTK programs use the latter
    # approach, so some modern input methods have bugs and misbehave when faced
    # with the way Emacs does it.
    #
    # A workaround is to set GTK_IM_MODULE=none in the environment, or maybe
    # find a different input method without these problems.
    export GTK_IM_MODULE=none
    echo "[INFO] Change GDK_BACKEND to wayland and GTK_IM_MODULE to none"
  fi

  local emacs_dir
  emacs_dir=$(dirname "$RUN_EMACS_BIN")
  export PATH="$emacs_dir:$PATH"

  if [[ -d "$PWD" ]]; then
    EMACS_ARGS_DICT+=(--chdir "$PWD")
  fi

  if [[ "$RUN_EMACS_FORCE" -eq 0 ]] && is-emacs-server-running; then
    EMACS_DAEMON=$(run-emacsclient-nowait -e '(daemonp)' || :)

    if [[ $EMACS_DAEMON == "t" ]]; then
      emacsclient -c
    fi

    exit 0
  else
    echo "[RUN]" "$RUN_EMACS_BIN" "${EMACS_ARGS_DICT[@]}" "$@"
    exec "$RUN_EMACS_BIN" "${EMACS_ARGS_DICT[@]}" "$@"
    # exec jemacs "${EMACS_ARGS_DICT[@]}" "$@"
  fi
}

main "$@"
