#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

MAIN_PROXY=""

set -e
set -u

export TSOCKS_CONF_FILE="$HOME/.tsocks.conf"
export HTTP_PROXY=''
export HTTPS_PROXY=''
export http_proxy=''
export https_proxy=''
export no_proxy=''

# shellcheck disable=SC2157
if [[ ~/.config.sh ]]; then
  # shellcheck disable=SC1090
  source ~/.config.sh
fi

if [[ "${ALL_PROXY:-}" = "" ]]; then
  if [[ $MAIN_PROXY != "" ]]; then
    export HTTP_PROXY="$MAIN_PROXY"
    export HTTPS_PROXY="$MAIN_PROXY"
    export http_proxy="$MAIN_PROXY"
    export https_proxy="$MAIN_PROXY"
  else
    if pgrep -x squid &>/dev/null; then
      read -r -i internet -p "User: " PROXY_USER
      read -r -s -p "Password: " PROXY_PASSWORD
      echo
      export http_proxy="http://${PROXY_USER}:${PROXY_PASSWORD}@127.0.0.1:3128"
      export https_proxy="$http_proxy"
      export HTTP_PROXY="$http_proxy"
      export HTTPS_PROXY="$https_proxy"

      exec esa ssh-add-exec "$@"
    else
      if type -P tsocks &>/dev/null && [[ -f "$TSOCKS_CONF_FILE" ]]; then
        exec esa ssh-add-exec tsocks "$@"
        exit 1
      fi
    fi
  fi
fi

exec esa ssh-add-exec "$@"
