#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

set -euf

UNIFIED_SPELL_FILE="$HOME/src/home-settings/work_cfg/home/.sync-spell-dict"
if ! [[ -f $UNIFIED_SPELL_FILE ]]; then
  UNIFIED_SPELL_FILE="$HOME/.sync-spell-dict"
fi

ASPELL_FILE="$HOME/.aspell.en.pws"
VIM_SPELL_FILE="$HOME/.vim-spell.en.utf8.add"
ENCHANT_DIR="$HOME/.config/enchant"
ENCHANT_FILE="$ENCHANT_DIR/en_US.dic"

# Internal variables
FIREFOX=0
THUNDERBIRD=0
VIM=0
ASPELL=0
ENCHANT=0

declare -a LIST_FIREFOX_DICTS=()
declare -a LIST_THUNDERBIRD_DICTS=()

#-------------------------------------------------------------------------------
# Error handler
#-------------------------------------------------------------------------------
# shellcheck disable=SC2317
error_handler() {
  local errno="$?"
  echo "Error: ${BASH_SOURCE[1]}:${BASH_LINENO[0]}" \
    "(${BASH_COMMAND} exited with status $errno)" >&2
  exit "${errno}"
}

trap "error_handler" ERR
set -o errtrace

#-------------------------------------------------------------------------------
# Atexit
#-------------------------------------------------------------------------------
TMP_FILE=$(mktemp)
ATEXIT_DONE=0
atexit() {
  trap - EXIT INT TERM HUP QUIT
  local errno="$?"
  if [[ "$ATEXIT_DONE" -eq 0 ]]; then
    if [[ -f "$TMP_FILE" ]]; then
      rm -f "$TMP_FILE" || true
    fi
    ATEXIT_DONE=1
  fi
  exit "$errno"
}
trap 'atexit' EXIT INT TERM HUP QUIT

#-------------------------------------------------------------------------------
# Get Mozilla dictionaries paths
#-------------------------------------------------------------------------------
get_mozilla_dicts_paths() {
  local search_dir
  for search_dir in "$@"; do
    if [[ -d "$search_dir" ]]; then
      find "$search_dir" -maxdepth 2 -name persdict.dat
    fi
  done
}

#-------------------------------------------------------------------------------
# Generate unified spell file
#-------------------------------------------------------------------------------
gen_unified_spell_file() {
  local item

  if [[ -f "$UNIFIED_SPELL_FILE" ]]; then
    cp "$UNIFIED_SPELL_FILE" "$TMP_FILE"
  else
    touch "$TMP_FILE"
  fi

  # ASPELL
  if [[ -f "$ASPELL_FILE" ]]; then
    FIRST_ASPELL_LINE=$(head -n 1 "$ASPELL_FILE")
    if echo "$FIRST_ASPELL_LINE" | grep -q "^personal_ws"; then
      (grep -v "^personal_ws" <"$ASPELL_FILE" || true) \
        >>"$TMP_FILE"
      echo "" >>"$TMP_FILE"
      ASPELL=1
    fi
  fi

  # VIM SPELL
  if [[ -f "$VIM_SPELL_FILE" ]]; then
    cat "$VIM_SPELL_FILE" >>"$TMP_FILE"
    echo "" >>"$TMP_FILE"
    VIM=1
  fi

  # ENCHANT (EMACS JINX)
  if [[ -f "$ENCHANT_FILE" ]]; then
    cat "$ENCHANT_FILE" >>"$TMP_FILE"
    echo "" >>"$TMP_FILE"
    ENCHANT=1
  fi

  # FIREFOX
  readarray -t LIST_FIREFOX_DICTS < \
    <(get_mozilla_dicts_paths "$HOME/.mozilla/firefox" \
      "$HOME/.var/app/org.mozilla.firefox/.mozilla/firefox")

  if [[ ${#LIST_FIREFOX_DICTS[@]} -gt 0 ]]; then
    FIREFOX=1
    for item in "${LIST_FIREFOX_DICTS[@]}"; do
      cat "$item" >>"$TMP_FILE"
      echo "" >>"$TMP_FILE"
    done
  fi

  # THUNDERBIRD
  readarray -t LIST_THUNDERBIRD_DICTS < \
    <(get_mozilla_dicts_paths "$HOME/.thunderbird" \
      "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird")

  if [[ ${#LIST_THUNDERBIRD_DICTS[@]} -gt 0 ]]; then
    THUNDERBIRD=1
    for item in "${LIST_THUNDERBIRD_DICTS[@]}"; do
      cat "$item" >>"$TMP_FILE"
      echo "" >>"$TMP_FILE"
    done
  fi

  # Unified spell file (Source of truth)
  # tr removes carriage returns before grep processes the text
  tr -d '\r' <"$TMP_FILE" | grep -v '^$' | grep -E "^[[:alpha:]'-]+$" \
    | LC_ALL=C sort -u >"$UNIFIED_SPELL_FILE"
}

#-------------------------------------------------------------------------------
# Generate software spell dictionary
#-------------------------------------------------------------------------------
gen_dict_from_unified_spell_file() {
  local item

  # ASPELL
  if [[ $ASPELL -ne 0 ]]; then
    if [[ "$FIRST_ASPELL_LINE" != *utf8 ]]; then
      # Remove all spaces in the end of FIRST_ASPELL_LINE
      FIRST_ASPELL_LINE="${FIRST_ASPELL_LINE%%*( )}"

      # Append utf8
      FIRST_ASPELL_LINE="$FIRST_ASPELL_LINE utf-8"
    fi

    echo "$FIRST_ASPELL_LINE" >"$ASPELL_FILE"

    cat "$UNIFIED_SPELL_FILE" >>"$ASPELL_FILE"
  fi

  if [[ $VIM -ne 0 ]]; then
    cat "$UNIFIED_SPELL_FILE" >"$VIM_SPELL_FILE"
  fi

  # ENCHANT (EMACS JINX)
  if [[ $ENCHANT -ne 0 ]]; then
    mkdir -p "$ENCHANT_DIR"
    cat "$UNIFIED_SPELL_FILE" >"$ENCHANT_FILE"
  fi

  # FIREFOX
  if [[ $FIREFOX -ne 0 ]]; then
    for item in "${LIST_FIREFOX_DICTS[@]}"; do
      cat "$UNIFIED_SPELL_FILE" >"$item"
    done
  fi

  # THUNDERBIRD
  if [[ $THUNDERBIRD -ne 0 ]]; then
    for item in "${LIST_THUNDERBIRD_DICTS[@]}"; do
      cat "$UNIFIED_SPELL_FILE" >"$item"
    done
  fi
}

# Removes lines from a file that are exactly equal to the value of $string
remove_exact_line() {
  local file="$1"
  local string="$2"
  if [[ -f $file ]]; then
    echo "Remove $string from: $file"
    awk -v s="$string" '$0 != s' "$file" >"$TMP_FILE" && mv "$TMP_FILE" "$file"
  fi
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------
main() {
  if [[ $# -eq 0 ]] || [[ $1 = sync ]]; then
    # Delete the legacy one
    rm -f ~/.spell-unified

    gen_unified_spell_file
    gen_dict_from_unified_spell_file

    if [[ $ASPELL -ne 0 ]]; then
      wc -l "$ASPELL_FILE"
    fi

    if [[ $VIM -ne 0 ]]; then
      wc -l "$VIM_SPELL_FILE"
    fi

    wc -l "$ENCHANT_FILE"

    if [[ $FIREFOX -ne 0 ]]; then
      for item in "${LIST_FIREFOX_DICTS[@]}"; do
        wc -l "$item"
      done
    fi

    if [[ $THUNDERBIRD -ne 0 ]]; then
      for item in "${LIST_THUNDERBIRD_DICTS[@]}"; do
        wc -l "$item"
      done
    fi

    echo
    echo "Success."
  elif [[ $1 = remove ]]; then
    remove_exact_line "$ASPELL_FILE" "$2"
    remove_exact_line "$UNIFIED_SPELL_FILE" "$2"
    remove_exact_line "$VIM_SPELL_FILE" "$2"
    remove_exact_line "$ENCHANT_FILE" "$2"

    local file

    # Firefox
    readarray -t LIST_FIREFOX_DICTS < \
      <(get_mozilla_dicts_paths "$HOME/.mozilla/firefox" \
        "$HOME/.var/app/org.mozilla.firefox/.mozilla/firefox")

    for file in "${LIST_FIREFOX_DICTS[@]}"; do
      remove_exact_line "$file" "$2"
    done

    # Thunderbird
    readarray -t LIST_THUNDERBIRD_DICTS < \
      <(get_mozilla_dicts_paths "$HOME/.thunderbird" \
        "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird")

    for file in "${LIST_THUNDERBIRD_DICTS[@]}"; do
      remove_exact_line "$file" "$2"
    done
  fi
}

main "$@"
