#!/usr/bin/env python
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
"Update cookiecutter in the current directory."

import distutils  # pylint: disable=W4901
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

from cookiecutter.main import cookiecutter

# Global variables
VERBOSE = False
DEBUG = False


def first_directory(parent_dir: os.PathLike) -> Optional[Path]:
    """Return the first directory inside parent_dir."""
    for item in Path(parent_dir).iterdir():
        if item.is_dir():
            return item

    raise FileNotFoundError(f"There are not directories in {parent_dir}")


def main():
    """The command-line interface."""
    cookiecutter_template_name = sys.argv[1]

    # Chdir to the project dir (Git toplevel directory)
    try:
        project_dir = \
            subprocess.check_output(["git", "rev-parse", "--show-toplevel"],
                                    text=True).splitlines()[0]
    except subprocess.CalledProcessError:
        sys.exit(1)
    else:
        if VERBOSE:
            print(f"[VERBOSE] Project: {project_dir}")

        project_dir = Path(project_dir)
        if not project_dir.is_dir():
            print(f"Error: The directory does not exist: {project_dir}",
                  file=sys.stderr)
            sys.exit(1)

        os.chdir(project_dir)

    # Git remote origin
    try:
        git_remote_origin = \
            subprocess.check_output(["git", "config", "remote.origin.url"],
                                    text=True).splitlines()[0]
    except subprocess.CalledProcessError:
        sys.exit(1)
    else:
        if VERBOSE:
            print(f"[VERBOSE] Remote origin: {git_remote_origin}")

        project_name = Path(git_remote_origin).with_suffix("").name
        if not project_name:
            print(("Error: The project name cannot be read from the "
                   "remote origin."),
                  file=sys.stderr)
            sys.exit(1)

        if VERBOSE:
            print("[VERBOSE] Project name:", project_name)

    # Git remote origin
    try:
        git_remote_origin = \
            subprocess.check_output(["git", "config", "remote.origin.url"],
                                    text=True).splitlines()[0]
    except subprocess.CalledProcessError:
        sys.exit(1)
    else:
        if VERBOSE:
            print(f"[VERBOSE] Remote origin: {git_remote_origin}")

    with tempfile.TemporaryDirectory() as temporary_dir:
        temp_path = Path(temporary_dir)
        if DEBUG:
            print(f"[DEBUG] Temporary directory created: {temp_path}")

        os.chdir(temporary_dir)

        cookiecutter(cookiecutter_template_name,
                     extra_context={'project_name': project_name},
                     no_input=True,
                     overwrite_if_exists=True,
                     directory=".",
                     skip_if_file_exists=False)

        template_dir = first_directory(temporary_dir)
        if DEBUG:
            print(f"[DEBUG] Template dir {template_dir}")

        distutils.dir_util.copy_tree(str(template_dir),
                                     str(project_dir))

    print(f"[SUCCESS] {project_dir}")


if __name__ == "__main__":
    main()
