#!/usr/bin/env python
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

"""Generate list of projects.

Currently used by Emacs."""

import os
import pathlib
import subprocess
from pathlib import Path

HOME_DIR = Path(str(pathlib.Path.home()))
PROJECTS_DIR = HOME_DIR / "src"
TXT_PROJECT_LIST = HOME_DIR / ".projects"

EMACS_PROJECT_LIST = HOME_DIR / ".emacs-data/var/projects-auto"
EMACS_PROJECTILE_LIST = HOME_DIR / ".emacs-data/var/projectile-auto.eld"

ADDITIONAL_PROJECTS = []


class LocalProjects:
    def __init__(self):
        self.delete_repo = False
        self.list_projects = []

        # Ensure ~/src exists
        os.makedirs(PROJECTS_DIR, exist_ok=True)
        # os.chdir(src_dir)

        for file_path in (EMACS_PROJECT_LIST, EMACS_PROJECTILE_LIST):
            os.makedirs(os.path.dirname(file_path), exist_ok=True)

    def add_project(self, project_dir: os.PathLike) -> None:
        """Add project to Emacs project lists."""
        home_dir_str = str(HOME_DIR)

        project_dir_str = str(project_dir)
        if project_dir_str.startswith(home_dir_str):
            project_dir_str = f"~{project_dir_str[len(home_dir_str):]}"

        self.list_projects.append(project_dir_str)

    def save(self):
        with open(TXT_PROJECT_LIST, "w", encoding="utf-8") as fhandler:
            for project in self.list_projects:
                fhandler.write(str(Path(project).expanduser()) +
                               "\n")

        for file_path in (EMACS_PROJECT_LIST, EMACS_PROJECTILE_LIST):
            # TODO: generate inside of a string before writing to a file
            with open(file_path, "w", encoding="utf-8") as fhandler:
                fhandler.write("(\n")

        with open(EMACS_PROJECT_LIST, "a",
                  encoding="utf-8") as fhandler:
            for project in self.list_projects:
                fhandler.write(f'("{project}")\n')

        with open(EMACS_PROJECTILE_LIST, "a",
                  encoding="utf-8") as fhandler:
            for project in self.list_projects:
                fhandler.write(f'"{project}"\n')

        for file_path in (EMACS_PROJECT_LIST, EMACS_PROJECTILE_LIST):
            with open(file_path, "a", encoding="utf-8") as f:
                f.write(")\n")

    def add_upstream(self, directory: str, url: str, remote_name: str) -> None:
        """Add upstream remote to repository."""
        if self.delete_repo:
            return

        try:
            upstream_url = subprocess.check_output(
                ["git", "-C", directory, "remote", "get-url", remote_name],
                stderr=subprocess.DEVNULL,
                text=True).splitlines()[0]
        except subprocess.CalledProcessError:
            upstream_url = ""

        if url != upstream_url:
            if upstream_url:
                subprocess.run(["git", "-C", directory, "remote", "remove",
                                remote_name], check=True)
            subprocess.run(["git", "-C", directory, "remote", "add",
                            remote_name, url], check=True)
            print(f"[ADD UPSTREAM: {remote_name}] {directory}: {url}")


def find_git_repositories(root_dir: os.PathLike) -> set:
    """Search recursively for all git repositories."""
    root_path = Path(root_dir)
    return {Path(git_dir.parent)
            for git_dir in root_path.rglob('.git') if git_dir.is_dir()}


def main():
    if PROJECTS_DIR:
        os.makedirs(PROJECTS_DIR, exist_ok=True)

    manager = LocalProjects()

    for git_repo in ADDITIONAL_PROJECTS:
        manager.add_project(git_repo)
    for git_repo in find_git_repositories(PROJECTS_DIR):
        parent = git_repo.parent
        try:
            subprocess.check_call(["git", "rev-parse", "--show-toplevel"],
                                  stdout=subprocess.DEVNULL,
                                  stderr=subprocess.DEVNULL,
                                  cwd=parent)
        except subprocess.CalledProcessError:
            # The parent directory is not a Git repository, indicating that it
            # is not a project within another project.
            manager.add_project(git_repo)

    manager.save()

    # with open(EMACS_PROJECT_LIST, "r", encoding="utf-8") as fhandler:
    #     for line in fhandler.readlines():
    #         print(line)
    print("Success.")


if __name__ == "__main__":
    import sys
    sys.exit(main())
