#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Copyright (C) 2004-2026 James Cherti
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#

# This have to be defined after sourcing profile and bashrc
# set -euf -o pipefail
set -e
set -u

EMACS_BIN="$HOME/.bin/run-emacs"

# # EMACS_BIN="$HOME/.bin/run-emacs-30"
# EMACS_BIN="$HOME/.bin/run-emacs-master"
# EMACS_BIN="$HOME/.bin/run-emacs-straight"
# EMACS_BIN="$HOME/.bin/run-emacs-elpaca"

is_wayland() {
    [[ $XDG_SESSION_TYPE = wayland ]] || return 1
}

is_gnome() {
    [[ $XDG_CURRENT_DESKTOP = GNOME ]] || return 1
}

has_run_or_raise() {
    test -d ~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz
}

bg_run() {
    # nohup
    # --chdir "$HOME" <- breaks ./apps in a different directory
    "$@" &
    disown
}

show_window() {
    local proc_name="$1"
    local win_name="$2"

    if is_wayland; then
        if pgrep "$proc_name" &>/dev/null; then
            echo "[IGNORE] The process $proc_name is already running"
            return 0
        fi
    else
        if wmctrl -x -a "$win_name"; then
            echo "[FOCUS WINDOW] $win_name"
            return 0
        elif [[ $# -gt 0 ]]; then
            shift
            shift
            echo "[RUN]" "$@"
            bg_run "$@"
        fi
    fi

    return 1
}

start-or-raise-emacs() {
    if pgrep --exact emacs &>/dev/null; then
        if is_wayland; then
            if is_gnome && has_run_or_raise; then
                gdbus call --session --dest org.gnome.Shell \
                    --object-path /org/gnome/Shell/Extensions/RunOrRaise \
                    --method org.gnome.Shell.Extensions.RunOrRaise.Call \
                    ",${EMACS_BIN},,/Lightemacs$/"
            else
                bg_run "$EMACS_BIN"
            fi
        else
            show_window emacs "emacs.Emacs" "$EMACS_BIN"
        fi
    else
        bg_run "$EMACS_BIN"
        # "$EMACS_BIN"
    fi
}

# TODO should this be added back
# cleanup-emacs() {
#     if [[ -d ~/.emacs.d/eln-cache/ ]]; then
#         rm -fr ~/.emacs.d/eln-cache/
#     fi
#
#     if [[ -d ~/.emacs.d/elpa/ ]]; then
#         rm -fr ~/.emacs.d/elpa/ &
#         disown
#     fi
# }

main() {
    # cleanup-emacs
    # Check if Emacs server is running
    cd
    start-or-raise-emacs
}

main "$@"
