#!/usr/bin/env bash
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

XDG_SESSION_TYPE="$XDG_SESSION_TYPE"

set -e
set -u

SCRIPT_NAME=xdevenv
XDEVENV_BIN="$0"

load_bashrc() {
  set +e
  set +u
  # shellcheck disable=SC1090
  _SH_PROFILE_LOCAL_LOADED=""
  _JC_PROFILE_LOADED=""
  if [[ -f ~/.profile ]]; then
    # shellcheck disable=SC1090
    source ~/.profile
  fi

  _JC_BASHRC_LOADED=""
  source ~/.bashrc
  set -e
  set -u
}

pulseaudio_set_volume() {
  local new_volume="$1"

  local current_volume
  current_volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -n 1)

  if [[ $((current_volume + new_volume)) -gt 100 ]]; then
    pactl set-sink-volume @DEFAULT_SINK@ '100%'
  else
    pactl set-sink-volume @DEFAULT_SINK@ "${new_volume}%"
  fi
}

pulseaudio_mute() {
  pactl set-sink-mute @DEFAULT_SINK@ toggle

  local msg
  msg=$(pactl get-sink-mute @DEFAULT_SINK@)
  notify "$msg"
}

pulseaudio_raise_volume() {
  # Increase the volume by 2%
  pulseaudio_set_volume '+2'
}

pulseaudio_lower_volume() {
  # Decrease the volume by 2%
  pulseaudio_set_volume '-2'
}

notify() {
  local msg
  msg="$1"
  shift

  if type -P notify-send >/dev/null 2>&1; then
    notify-send "$@" -a "$SCRIPT_NAME" "$SCRIPT_NAME" "$msg" || true
  fi

  echo "$msg"
}

has_run_or_raise() {
  test -d ~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz
}

run-renice-all() {
  # Conflict with ananicy
  if [[ -f /usr/local/bin/renice-all ]] && type -P sudo &>/dev/null; then
    (sleep 5 && sudo /usr/local/bin/renice-all) &
    disown
    # export GTK_THEME_VARIANT="dark"
  fi
}

# legacy_xdotool_activate_window() {
#   local win_class="$1"
#   local errno=1

#   readarray -t list_win_pid < <(wmctrl -lx | awk "{ if(\$3 == \"$win_name\") { print \$1 } }")
#   if [[ ${#list_win_pid[@]} -lt 1 ]]; then
#     return 1
#   fi

#   local win_pid
#   for win_pid in "${list_win_pid[@]}"; do
#     echo "$win_pid"
#     xdotool windowactivate "$win_pid" >/dev/null 2>&1 && errno=0
#   done

#   return "$errno"
# }

# legacy_xdotool_show_window() {
#   local win_class="$1"
#   shift
#   local xdotool_activate_window_cmd=("xdotool_activate_window" "--onlyvisible" "--class" "$win_class")

#   if ! "${xdotool_activate_window_cmd[@]}" >/dev/null 2>&1; then
#     echo "[RUN]" "$@" >&2
#     nohup "$@" >/dev/null 2>&1 &

#     local i
#     for ((i = 0; i < 100; i++)); do
#       if "${xdotool_activate_window_cmd[@]}" >/dev/null 2>&1; then
#         # First execution
#         return 2
#       fi
#       sleep 0.1
#     done

#     # For some reason, the window cannot be activated
#     return 1
#   fi

#   return 0
# }

is_xfce() {
  [[ $XDG_CURRENT_DESKTOP = XFCE ]] && return 0
  return 1
}

# is_kde() {
#   [[ $XDG_CURRENT_DESKTOP = KDE ]] && return 0
#   return 1
# }

is_gnome() {
  [[ $XDG_CURRENT_DESKTOP = GNOME ]] && return 0
  return 1
}

bg_run() {
  # nohup
  # --chdir "$HOME" <- breaks ./apps in a different directory
  /usr/bin/env "$@" &>/dev/null &
  disown
}

# remove_title_bar() {
#   local win_name="$1"
#   shift
#   readarray -t list_win_pid < <(wmctrl -lx | awk "{ if(\$3 == \"$win_name\") { print \$1 } }")
#   # readarray -t list_win_pid < <(xdotool search --class "$win_name")
#   if [[ ${#list_win_pid[@]} -le 0 ]]; then
#     return 0
#   fi

#   local win_pid
#   for win_pid in "${list_win_pid[@]}"; do
#     xprop -id "$win_pid" -format _MOTIF_WM_HINTS 32i -set _MOTIF_WM_HINTS "0x2, 0x0, 0x0, 0x0, 0x0" || true
#     # xprop -id "$win_pid" -format _MOTIF_WM_HINTS 32i -set _MOTIF_WM_HINTS 2 || true
#   done

#   echo "[INFO] Remove title bar of: $win_name"
# }

# standard_win_name() {
#   # Emacs.emacs -> Emacs
#   sed -e 's/\..*$//'
# }

# set -o xtrace
is_wayland() {
  if [[ $XDG_SESSION_TYPE = wayland ]]; then
    return 0
  fi

  return 1
}

show_window() {
  local proc_name="$1"
  local win_name="$2"

  if is_wayland; then
    if pgrep --quiet -x "$proc_name"; then
      echo "[IGNORE] The process $proc_name is already running"
      return 0
    fi
  fi

  if wmctrl -x -a "$win_name"; then
    echo "[FOCUS WINDOW] $win_name"
    return 0
  elif [[ $# -gt 0 ]]; then
    shift
    shift
    echo "[RUN]" "$@"
    bg_run "$@"
  fi
  return 1
}

win_wait() {
  local win_name="$1"
  for ((i = 0; i < 100; i++)); do
    if wmctrl -x -a "$win_name"; then
      return 0
    fi
    sleep 0.1
  done
  return 1
}

# maximize() {
#   local win_name="$1"
#   wmctrl -x -a "$win_name" -b add,maximized_vert,maximized_horz
# }

show_window_maximized() {
  local proc_name="$1"
  local win_name="$2"
  if ! show_window "$@"; then
    if ! is_wayland; then
      win_wait "$win_name"
      wmctrl -x -a "$win_name" -b add,maximized_vert,maximized_horz
    fi
    return 1
  else
    if [[ $XDEVENV_ALWAYS_MAXIMIZE = 1 ]]; then
      if ! is_wayland; then
        wmctrl -x -a "$win_name" -b add,maximized_vert,maximized_horz
      fi
    fi
  fi

  return 0
}

show_window_maximized_devilspie() {
  if pgrep --quiet -x devilspie2; then
    show_window "$@" || return 1
    return 0
  fi

  show_window_maximized "$@" || return 1
  return 0
}

# show_window_fullscreen() {
#   local win_name="$1"
#   if ! show_window "$@"; then
#     win_wait "$win_name"
#     wmctrl -x -a "$win_name" -b add,maximized_vert,maximized_horz
#     wmctrl -x -a "$win_name" -b add,fullscreen
#   else
#     if [[ $XDEVENV_ALWAYS_MAXIMIZE = 1 ]]; then
#       wmctrl -x -a "$win_name" -b add,maximized_vert,maximized_horz
#       wmctrl -x -a "$win_name" -b add,fullscreen
#     fi
#   fi
# }

disable_gnome_tracker() {
  if ! type -P systemctl >/dev/null 2>&1; then
    return 0
  fi

  if [[ $XDG_CURRENT_DESKTOP = GNOME ]]; then
    local service
    local error=0
    for service in tracker-store tracker-miner-fs tracker-miner-rss \
      tracker-extract tracker-miner-apps tracker-writeback; do
      if ! systemctl --user list-unit-files | grep masked \
        | grep -q -E "^${service}.service"; then
        echo "Mask: $service"
        systemctl --user mask "${service}.service" >/dev/null || error=1
      fi
    done

    return "$error"
  else
    echo "Error: Run this in a GNOME session" >&2
  fi
}

enable_gnome_tracker() {
  if ! type -P systemctl >/dev/null 2>&1; then
    return 0
  fi

  if [[ $XDG_CURRENT_DESKTOP = GNOME ]]; then
    local service
    local error=0
    for service in tracker-store tracker-miner-fs tracker-miner-rss \
      tracker-extract tracker-miner-apps tracker-writeback; do
      if ! systemctl --user list-unit-files | grep masked \
        | grep -q -E "^${service}.service"; then
        echo "Mask: $service"
        systemctl --user unmask "${service}.service" >/dev/null || error=1
      fi
    done

    return "$error"
  else
    echo "Error: Run this in a GNOME session" >&2
  fi
}

main() {
  USER=$(id -un)
  HOME=$(eval echo "~$USER")

  [[ -z ${XDEVENV_ALWAYS_MAXIMIZE+x} ]] && XDEVENV_ALWAYS_MAXIMIZE=0
  [[ -z ${XDG_SESSION_TYPE+x} ]] && XDG_SESSION_TYPE=""
  [[ -z ${DESKTOP_SESSION+x} ]] && DESKTOP_SESSION=""

  if [[ $XDG_SESSION_TYPE = wayland ]]; then
    export QT_QPA_PLATFORM=wayland
  fi

  local cmd_name
  for cmd_name in wmctrl tmux borg; do
    if ! type -P "$cmd_name" >/dev/null 2>&1; then
      notify "The command '$cmd_name' does not exist."
      exit 1
    fi
  done

  if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <name>" >&2
    exit 1
  fi

  case "$1" in
  startup-apps)
    set +e

    if is_xfce \
      && type -P xmodmap &>/dev/null \
      && type -P setxkbmap &>/dev/null; then
      # setxkbmap -option
      setxkbmap -option caps:hyper
      xmodmap -e "keysym Hyper_L = Mode_switch"
      xmodmap -e "keysym h = h H Left"
      xmodmap -e "keysym j = j J Down"
      xmodmap -e "keysym k = k K Up"
      xmodmap -e "keysym l = l L Right"
      xmodmap -e "keysym f = f F Next"
      xmodmap -e "keysym b = b B Prior"
    fi

    # enable_gnome_tracker

    # Init
    lsmod | grep -q "nvidia" && type -P nvidia-settings &>/dev/null \
      && nvidia-settings --load-config-only

    BUCKLE_OPTS=()

    if is_xfce && type -P picom &>/dev/null; then
      bg_run "$0" picom
    fi

    if is_xfce && type -P xfconf-query &>/dev/null; then
      xfconf-query --create -c 'xfce4-power-manager' \
        -p '/xfce4-power-manager/presentation-mode' \
        --type 'bool' --set 'false'
    fi

    if is_xfce && type -P redshift &>/dev/null; then
      redshift -x
      redshift -o
    fi

    bg_run "$0" pwd-manager
    # bg_run "$0" web-browser
    # bg_run "$0" editor
    bg_run "$0" terminal
    ;;

  web-browser)
    export MOZ_USE_XINPUT2="0" # Disable it

    if type -P firefox &>/dev/null; then
      # Does MOZ_X11_EGL option cause issues?
      # export MOZ_X11_EGL=1
      if has_run_or_raise && is_gnome && is_wayland; then
        gdbus call --session --dest org.gnome.Shell \
          --object-path /org/gnome/Shell/Extensions/RunOrRaise \
          --method org.gnome.Shell.Extensions.RunOrRaise.Call \
          ",gtk-launch firefox.desktop,firefox"
      else
        show_window_maximized firefox Navigator.firefox firejail firefox
      fi
    # elif type -P midori &>/dev/null; then
    #   show_window midori midori.Midori firejail midori
    elif type -P apt-get &>/dev/null; then
      show_window_maximized chromium chromium.Chromium firejail chromium \
        --profile=chromium \
        --enable-features=VaapiVideoDecoder \
        --start-maximized --password-store=basic
    fi

    # run-renice-all

    ;;

  enable-gnome-tracker)
    enable_gnome_tracker
    ;;

  disable-gnome-tracker)
    disable_gnome_tracker
    ;;

  web-browser-profiles)
    # show_window firefox Firefox.firefox firejail firefox -P
    bg_run firejail firefox -P
    # run-renice-all
    ;;

  chromium)
    # If running this inside a function or script
    if flatpak info com.google.Chrome >/dev/null 2>&1; then
      flatpak run com.google.Chrome \
        --enable-features=VaapiVideoDecoder \
        --start-maximized \
        --password-store=basic \
        "$@"
    else
      echo "Error: com.google.Chrome Flatpak is not installed." >&2
    fi

    # local name
    # for name in chromium chromium-bin; do
    #   firejail --profile=chromium "$name" \
    #     --enable-features=VaapiVideoDecoder \
    #     --start-maximized --password-store=basic
    #   break
    # done
    ;;

  file-explorer)
    if type -P thunar &>/dev/null; then
      if has_run_or_raise && is_gnome && is_wayland; then
        gdbus call --session --dest org.gnome.Shell \
          --object-path /org/gnome/Shell/Extensions/RunOrRaise \
          --method org.gnome.Shell.Extensions.RunOrRaise.Call \
          ",gtk-launch thunar,thunar,"
      else
        show_window thunar thunar.Thunar thunar
      fi
    elif type -P nautilus &>/dev/null; then
      show_window nautilus org.gnome.Nautilus.Org.gnome.Nautilus nautilus "$HOME"
    elif type -P dolphin &>/dev/null; then
      show_window dolphin dolphin.dolphin dolphin "$HOME"
    elif type -P pcmanfm &>/dev/null; then
      show_window pcmanfm pcmanfm.Pcmanfm pcmanfm "$HOME"
    fi
    ;;

  mail-client)
    if type -P thunderbird; then
      if has_run_or_raise && is_gnome && is_wayland; then
        gdbus call --session --dest org.gnome.Shell \
          --object-path /org/gnome/Shell/Extensions/RunOrRaise \
          --method org.gnome.Shell.Extensions.RunOrRaise.Call \
          ",gtk-launch org.mozilla.Thunderbird,thunderbird,"
      else
        show_window thunderbird Thunderbird firejail thunderbird
      fi
    fi
    ;;

  pwd-manager)
    if type -P keepassxc; then
      if [[ $XDG_SESSION_TYPE = wayland ]]; then
        keepassxc
      else
        show_window keepassxc keepassxc.KeePassXC keepassxc
      fi
    fi
    ;;

  screenshot)
    if type -P flameshot; then
      bg_run flameshot gui
    elif type -P xfce4-screenshooter; then
      bg_run xfce4-screenshooter --region
    fi
    ;;

  mpv)
    show_window mpv "gl.mpv" mpv --player-operation-mode=pseudo-gui
    ;;

  emacs-terminal)
    if pgrep --quiet -x emacs; then
      "$0" emacs
      emacsclient --no-wait -e '(best-tmux-run)'
      exit 0
    fi
    ;;

  picom)
    if type -P xfconf-query &>/dev/null; then
      USE_COMPOSING=(xfconf-query -c 'xfwm4' -p '/general/use_compositing'
        --type 'bool')

      if [[ $USE_COMPOSING = true ]]; then
        xfconf-query --create -c 'xfwm4' -p '/general/use_compositing' \
          --type 'bool' --set 'false'
        sleep 1
      fi
    fi

    cd
    bg_run picom
    ;;

  terminal)
    # exec "$0" emacs-terminal
    TERMINATOR_OPTIONS_STR="--borderless"
    TERMINATOR_OPTS=(--borderless)
    TERMINATOR_OPTS_STR=--borderless

    TMUX_CMD="$HOME/.local/bin/tmux-session xdevenv"
    TMUX_CMD_LIST=("$HOME/.local/bin/tmux-session" xdevenv)
    # TMUX_CMD="bash -c 'tmux-session xdevenv'"
    # TMUX_CMD_LIST=(bash -c 'tmux-session xdevenv')
    # TMUX_CMD="bash -c 'tmux -2 attach-session -t xdevenv || tmux -2 new -s xdevenv'"
    # TMUX_CMD_LIST=(bash -c 'tmux -2 attach-session -t xdevenv || tmux -2 new -s xdevenv')
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
    VIRTUAL_ENV=""
    TERMINAL_CMD=()
    if has_run_or_raise && is_gnome && is_wayland; then
      if type -P terminator; then
        gdbus call --session --dest org.gnome.Shell \
          --object-path /org/gnome/Shell/Extensions/RunOrRaise \
          --method org.gnome.Shell.Extensions.RunOrRaise.Call \
          ",terminator $TERMINATOR_OPTS_STR --title=tmux --execute $TMUX_CMD,terminator,"
      fi
    else
      if type -P terminator; then
        # TERMINAL_OPTS=(--maximize --borderless)
        local win_name="terminator.Terminator"
        TERMINAL_CMD=(show_window_maximized_devilspie terminator "$win_name"
          terminator "${TERMINATOR_OPTS[@]}"
          --title=tmux --execute "${TMUX_CMD_LIST[@]}")
      elif type -P gnome-terminal >/dev/null 2>&1; then
        # GNOME_TERMINAL_OPTS=(--maximize --hide-menubar)
        GNOME_TERMINAL_OPTS=(--hide-menubar)
        # GNOME_TERMINAL_OPTS=(--full-screen)
        local win_name="gnome-terminal-server.Gnome-terminal"
        # show_window_maximized_devilspie "$win_name" gnome-terminal "${GNOME_TERMINAL_OPTS[@]}" --title=tmux -e 'sh -c "tmux -2 attach || TERM=xterm-256color tmux -2"'
        TERMINAL_CMD=(show_window_maximized_devilspie gnome-terminal "$win_name" gnome-terminal "${GNOME_TERMINAL_OPTS[@]}" --title=tmux -e "$TMUX_CMD")
      elif type -P konsole &>/dev/null; then
        TERMINAL_OPTS=(--hide-tabbar --hide-menubar)
        local win_name="konsole.konsole"
        TERMINAL_CMD=(
          show_window_maximized_devilspie konsole "$win_name"
          konsole "${TERMINAL_OPTS[@]}" -e "${TMUX_CMD_LIST[@]}"
        )
      elif type -P tilix; then
        TERMINAL_OPTS=(--window-style=borderless)
        local win_name="tilix.Tilix"
        TERMINAL_CMD=(show_window_maximized_devilspie tilix "$win_name" tilix "${TERMINAL_OPTS[@]}" --title=tmux -e "$TMUX_CMD")
      elif type -P xfce4-terminal >/dev/null 2>&1; then
        XFCE_TERMINAL_OPTS=(--hide-menubar --hide-scrollbar) # --hide-borders
        # XFCE_TERMINAL_OPTS+=(--maximize)
        # XFCE_TERMINAL_OPTS+=(--fullscreen)
        local win_name="xfce4-terminal.Xfce4-terminal"
        TERMINAL_CMD=(show_window_maximized_devilspie xfce4-terminal "$win_name" xfce4-terminal "${XFCE_TERMINAL_OPTS[@]}" --title=tmux -e "$TMUX_CMD")
      fi

      ERRNO=0
      if [[ "${#TERMINAL_CMD[@]}" -gt 0 ]]; then
        "${TERMINAL_CMD[@]}" || ERRNO="$?"
      fi
    fi
    ;;

  draw)
    show_window_maximized soffice libreoffice.libreoffice-draw libreoffice --draw
    ;;

  pdf)
    show_window_maximized evince evince.Evince evince
    ;;

  night)
    if is_gnome; then
      gsettings set org.gnome.settings-daemon.plugins.color \
        night-light-enabled true
    fi

    if ! is_gnome && type -P redshift >/dev/null 2>&1; then
      set +e
      pkill redfish
      redshift -x
      redshift -o
      set -e
    fi
    ;;

  light)
    if is_gnome; then
      gsettings set org.gnome.settings-daemon.plugins.color \
        night-light-enabled false
    fi

    if is_xfce && type -P redshift >/dev/null 2>&1; then
      set +e
      pkill redfish
      redshift -x
      # if type -P xgamma &>/dev/null; then
      #   xgamma -gamma 0.7
      # fi
      set -e
    fi
    ;;

  xocrshot)
    ~/.local/bin/xocrshot >~/toto 2>&1
    ;;

  emacs)
    exec ~/.bin/xdevenv-emacs
    ;;

  vim)
    # 1. If you are using GTK3 and Vim appears to be slow, try setting the environment
    # variable $GDK_RENDERING to "image".
    # :help gtk3-slow
    local vim_env=''
    if is_xfce; then
      vim_env="$vim_env GDK_RENDERING=image"
    fi

    #
    # 2. -u ~/.vimrc makes vim ignore /etc/vim/
    local vim_cmd=(bash -i -c "VIM_PERSISTENT_SESSION_ENABLED=1${vim_env} gvim -u ~/.vimrc --servername GMAIN")

    load_bashrc
    # export VIM_PERSISTENT_SESSION_ENABLED=1
    # export GDK_RENDERING=image
    # local vim_cmd=(gvim -u ~/.vimrc --servername GMAIN)

    local win_name="gvim.Gvim"
    if ! show_window_maximized_devilspie gvim "$win_name" "${vim_cmd[@]}"; then
      # First time
      true
      # remove_title_bar "$win_name"
    fi
    ;;

  editor)
    load_bashrc
    # echo "--cycle -i --multi --exact --bind alt-j:down,alt-k:up"
    exec "$0" emacs
    # exec "$0" vim
    ;;

  gdm-change-user)
    gdbus call \
      --system \
      --object-path /org/gnome/DisplayManager/LocalDisplayFactory \
      --dest org.gnome.DisplayManager \
      --method org.gnome.DisplayManager.LocalDisplayFactory.CreateTransientDisplay \
      >/dev/null
    # fi
    ;;

  pavucontrol)
    show_window pavucontrol "pavucontrol.Pavucontrol" "pavucontrol"
    ;;

  terminal-tmux-run)
    echo "[TASK] terminal"
    "$XDEVENV_BIN" terminal || true

    local i
    for ((i = 0; i < 15; i++)); do
      len_tmux_sessions=$(tmux list-sessions | wc -l) || break
      if [[ $len_tmux_sessions -gt 0 ]]; then
        break
      fi
      sleep 0.25
    done

    shift
    echo "[TASK] tmux-run" "$@"
    ERRNO=0
    tmux-run "$@" || ERRNO="$?"
    exit "$ERRNO"
    ;;

  suspend)
    local process
    for process in emerge pacman wget curl aria2c apt-get git scp rsync borg; do
      if pgrep --quiet -x "$process"; then
        notify "You cannot suspend because of '$process'"
        exit 1
      fi
    done
    systemctl suspend
    ;;

  xfce4-toggle-composing)
    local status
    status=$(xfconf-query --create -c 'xfwm4' -p '/general/use_compositing' --type 'bool')
    if [[ $status = false ]]; then
      status='true'
      notify "ENABLE Compositor"
    else
      status='false'
      notify "DISABLE Compositor"
    fi

    xfconf-query --create -c 'xfwm4' -p '/general/use_compositing' --type 'bool' --set "$status"
    ;;

  volume-up)
    pulseaudio_raise_volume
    ;;

  volume-down)
    pulseaudio_lower_volume
    ;;

  volume-mute)
    pulseaudio_mute
    ;;
  *)
    echo "Error: '$1' is not supported." >&2
    exit 1
    ;;
  esac

  exit 0
}

main "$@"

# vim:foldmethod=indent
