#!/bin/bash
#
# Check GPG signatures of all Git commits.
#
# Author: James Cherti
# URL: https://github.com/jamescherti/jc-dev
#
# Distributed under terms of the MIT license.
#
# Copyright (C) 2004-2026 James Cherti
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -uf -o pipefail
IFS=$'\n\t'

main() {
  local amount_commits=0
  local commit=""
  local error=0
  local list_commits=()

  readarray -t list_commits < <(git rev-list HEAD)
  if [[ ${#list_commits[@]} -eq 0 ]]; then
    echo
    echo "Error: no commits were found in the directory '$(pwd)'." >&2
    exit 1
  fi

  for commit in "${list_commits[@]}"; do
    if ! git verify-commit "$commit" >/dev/null 2>&1; then
      error=$((error + 1))
      break
    fi
    amount_commits=$((amount_commits + 1))
  done

  if [[ $error = 0 ]]; then
    echo "[SUCCESS] GPG signatures of all the commits are valid ($amount_commits commits)."
  else
    echo "[ERROR] Error with:"
    git show --show-signature "$commit"
    echo
    echo "[ERROR] Failed to validate the GPG signature of the commit: $commit" >&2
    exit 1
  fi

  exit 0
}

main "$@"
